### ISSUE TITLE
Cannot pickle lambdas from SymPy

### ISSUE THREAD

**Issue by parnmatt** [uqfoundation/dill#104]
I have been using SymPy recently. Anonymous functions can be generated using `sympy.lambdify`.
I required to store these for later, as they can be computationally expensive to generate the expressions in the first place; i.e., solving an ODE system symbolically.

`dill` came to mind as I have previously used it to pickle a lambda, however it was giving errors. Here is a minimalistic example of a simple function:

```python
import sympy
import dill

# use basic session, puts multiple symbols in scope
sympy.init_session()

# create expression, simple for example
expr = 2*x + y

# generate anonymous function
func = sympy.lambdify((x, y), expr)

print(func(5, 6))  #=> prints 16

# pickle file
pickled_func = dill.dumps(func)
```
Where I get a big error that traces back to:
> PicklingError: Can't pickle : it's not found as mpmath.ctx_mp_python.constant

Now I thought this maybe an issue with how SymPy generates the function, however `cloudpickle` was able to successfully pickle the function:

```python
import pickle
import cloudpickle

print(pickle.loads(cloudpickle.dumps(func))(5, 6))  #=> prints 16
```

It was brought to my attention that this may be unexpected behaviour with how `dill` interprets lambdas of objects; and thus you should be made aware.

**Comment by mmckerns** [comment]
If you use the flag `recurse=True` on `dumps`, `dill` can pickle your `func` (see #86).  This behavior will likely become the default setting once #105 is resolved.

**Comment by mmckerns** [comment]
added global setting `dill.settings['recurse']`

**Comment by mvanvleet** [comment]
Related issue to OP: while dill now can pickle most sympy functions, I run into pickling errors depending on my choice of the modules optional argument. Here's a minimal working example based on OP's example:

```python
import sympy
import dill

dill.settings['recurse'] = True

# put multiple symbols in scope
x, y, z = sympy.symbols('x y z')

# create expression, simple for example
expr = sympy.sqrt(2*x) + y

# generate anonymous function
#func = sympy.lambdify((x, y), expr,modules='numpy')   # This fails
func = sympy.lambdify((x, y), expr,modules='numexpr')  # This works

# pickle and unpickle lambda expression
pickled_func = dill.dumps(func)
new_func = dill.loads(pickled_func)
print new_func(2,2)

```

Using `modules='numexpr'` works fine, however using `modules='numpy'` results in the following error:

```python

Traceback (most recent call last):
  File "test.py", line 17, in <module>
    pickled_func = dill.dumps(func)
  File "/home/mvanvleet/anaconda2/lib/python2.7/site-packages/dill/dill.py", line 281, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/home/mvanvleet/anaconda2/lib/python2.7/site-packages/dill/dill.py", line 274, in dump
    pik.dump(obj)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mvanvleet/anaconda2/lib/python2.7/site-packages/dill/dill.py", line 1363, in save_function
    obj.__dict__), obj=obj)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 401, in save_reduce
    save(args)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mvanvleet/anaconda2/lib/python2.7/site-packages/dill/dill.py", line 1098, in save_cell
    pickler.save_reduce(_create_cell, (f,), obj=obj)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 401, in save_reduce
    save(args)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mvanvleet/anaconda2/lib/python2.7/site-packages/dill/dill.py", line 871, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 422, in save_reduce
    self._batch_setitems(dictitems)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 686, in _batch_setitems
    save(k)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mvanvleet/anaconda2/lib/python2.7/site-packages/dill/dill.py", line 1299, in save_type
    StockPickler.save_global(pickler, obj)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 759, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <type 'numpy.uint64'>: it's not the same object as numpy.uint64

```

Any ideas what might be causing this error, and if it's fixable? In case it's helpful to know, I'm using Anaconda2-5.0.1-Linux-x86_64 with the following package versions:

```python
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct 16 2017, 17:29:19)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.__version__
'1.1.2.dev'
>>> import dill
>>> dill.__version__
'0.2.7.1'
```

**Comment by mmckerns** [comment]
@mvanvleet: would you mind deleting your comment and posting it as a new issue?  You can always refer back to this issue with a link.
