### ISSUE TITLE
compatibility with python3 (PyCapsule)?

### ISSUE THREAD

**Issue by nbecker** [uqfoundation/dill#106]
Attempting to write:

```
    from dill import load, dump
    try:
        intrlv_dict = load (open ('interlv.pickle', 'rb'))
    except:
        intrlv_dict = {}
```

At this point, the file 'interlv.pickle' does not exist, so intrlv_dict is {}

```
    try:
        intrlv = intrlv_dict[N]
    except:
        from srand_intrlv import srand_intrlv
        n = N
        s = int(sqrt(n/2))
        print ('generating interleaver:', n, s)
        intrlv = srand_intrlv (rs, n, s) << this is a numpy.ndarray
        intrlv_dict[n] = intrlv  
        dump (intrlv_dict, open ('interlv.pickle', 'wb'), -1)
```

Traceback (most recent call last):

```
  File "./test_unframed_multi_acic.py", line 1498, in <module>
    run_line (sys.argv)
  File "./test_unframed_multi_acic.py", line 1494, in run_line
    return run (opt, cmdline)
  File "./test_unframed_multi_acic.py", line 337, in run
    dump (intrlv_dict, open ('interlv.pickle', 'wb'), -1)
  File "/home/nbecker/.local/lib/python3.4/site-packages/dill/dill.py", line 182, in dump
    pik.dump(obj)
  File "/usr/lib64/python3.4/pickle.py", line 410, in dump
    self.save(obj)
  File "/usr/lib64/python3.4/pickle.py", line 477, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/nbecker/.local/lib/python3.4/site-packages/dill/dill.py", line 658, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib64/python3.4/pickle.py", line 812, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib64/python3.4/pickle.py", line 843, in _batch_setitems
    save(v)
  File "/usr/lib64/python3.4/pickle.py", line 522, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib64/python3.4/pickle.py", line 600, in save_reduce
    save(func)
  File "/usr/lib64/python3.4/pickle.py", line 477, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/nbecker/.local/lib/python3.4/site-packages/dill/dill.py", line 781, in save_builtin_method
    pickler.save_reduce(_get_attr, (obj.__self__, obj.__name__), obj=obj)
  File "/usr/lib64/python3.4/pickle.py", line 601, in save_reduce
    save(args)
  File "/usr/lib64/python3.4/pickle.py", line 477, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python3.4/pickle.py", line 727, in save_tuple
    save(element)
  File "/usr/lib64/python3.4/pickle.py", line 477, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/nbecker/.local/lib/python3.4/site-packages/dill/dill.py", line 949, in save_module
    state=_main_dict)
  File "/usr/lib64/python3.4/pickle.py", line 625, in save_reduce
    save(state)
  File "/usr/lib64/python3.4/pickle.py", line 477, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/nbecker/.local/lib/python3.4/site-packages/dill/dill.py", line 658, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib64/python3.4/pickle.py", line 812, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib64/python3.4/pickle.py", line 838, in _batch_setitems
    save(v)
  File "/usr/lib64/python3.4/pickle.py", line 522, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib64/python3.4/pickle.py", line 557, in save_reduce
    save(cls)
  File "/usr/lib64/python3.4/pickle.py", line 477, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/nbecker/.local/lib/python3.4/site-packages/dill/dill.py", line 993, in save_type
    StockPickler.save_global(pickler, obj)
  File "/usr/lib64/python3.4/pickle.py", line 913, in save_global
    (obj, module_name, name))
_pickle.PicklingError: Can't pickle <class 'PyCapsule'>: it's not found as builtins.PyCapsule
```

**Comment by nbecker** [comment]
This code works if I change dill to pickle

**Comment by matsjoyce** [comment]
Similar to #93, seems to be quite a common problem.

**Comment by mmckerns** [comment]
A `PyCapsule` is not an object that we explicitly handle in `dill`, and has become a fundamental object, on the level of `PyCObject`.  We might have to work with `ctypes` and the python/C API to make sure it's handled correctly in `dill`.

See: http://stackoverflow.com/questions/22497295/how-to-deal-with-pycapsule-type-inside-python

And for more information:
http://stackoverflow.com/questions/8436578/passing-a-c-pointer-around-with-the-python-c-api

**Comment by akshayka** [comment]
Any updates on this?

**Comment by mmckerns** [comment]
@akshayka: Nope, no one has addressed this issue yet.

**Comment by mdepitta** [comment]
As of dill version 0.3.1.1 this issue appears to be somehow related with numpy versions >1.16.4 where, apparently, dilling of np.arange(3) provide the error, but not dilling of list [0,1,2] for example. Right now I am sticking to `numpy` 1.16.4 but I hope a solution to this issue is provided soon.

**Comment by mmckerns** [comment]
@mdepitta: I don't see the issue with `np.arange(3)` for recent `numpy` and recent `dill`.  I do know that `PyCapsule` still aren't serializable.  I checked:
```
>>> import numpy as np
>>> import dill
>>> a = dill.dumps(np.arange(3))
>>> dill.loads(a)
array([0, 1, 2])
>>> np.__version__
'1.17.4'
>>> dill.__version__
'0.3.2.dev0'
```
Still looking into `PyCapsule`, however.

**Comment by mmckerns** [comment]
Easy way to produce a PyCapsule object:
```
Python 3.6.10 (default, Dec 21 2019, 11:39:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> import ctypes
>>> pycapsule = ctypes.pythonapi.PyCapsule_New
>>> pycapsule.restype = ctypes.py_object
>>> c = pycapsule()
>>> c   
\ufffd" at 0x1040f2330>d\ufffdtcH\ufffd
>>> type(c)
<class 'PyCapsule'>
>>> dill.dumps(c)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python3.6/site-packages/dill-0.3.2.dev0-py3.6.egg/dill/_dill.py", line 265, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "/Users/mmckerns/lib/python3.6/site-packages/dill-0.3.2.dev0-py3.6.egg/dill/_dill.py", line 259, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/Users/mmckerns/lib/python3.6/site-packages/dill-0.3.2.dev0-py3.6.egg/dill/_dill.py", line 445, in dump
    StockPickler.dump(self, obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 496, in save
    rv = reduce(self.proto)
TypeError: can't pickle PyCapsule objects
```

**Comment by mdepitta** [comment]
@mmckerns The issue I pointed out appears to be obsolete by now. I was able to solve after some testing by a full upgrade from `python-2.x` to `python-3.x` and upgrade of `dill` with the Python scientific stack accordingly. Thanks for your effort. Still looking for `PyCapsule` pickling.

**Comment by mmckerns** [comment]
I'm going to void this issue out and open up a more direct open-ended one in #354
