### ISSUE TITLE
Is there a way to pickle lambdas created in a repl?

### ISSUE THREAD

**Issue by maximilianr** [uqfoundation/dill#108]
Currently, running `a` from an different environment will fail. Is there a way to make this work, by pickling the function in a way that stores its code rather than its reference?

Thanks

```python
In [25]: def a(n):
   ....:     return n+1
   ....: 

In [26]: dill.dumps(a)
F1: <function a at 0x7f377d2b5c80>
F2: <function _create_function at 0x7f378d74e848>
Co: <code object a at 0x7f377d375eb0, file "<ipython-input-25-e0be1c309720>", line 1>
F2: <function _unmarshal at 0x7f378d74e6e0>
D1: <dict object at 0x7f37975605c8>
D2: <dict object at 0x7f377d1425c8>
Out[26]: '\x80\x02cdill.dill\n_create_function\nq\x00(cdill.dill\n_unmarshal\nq\x01Uxc\x01\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00C\x00\x00\x00s\x08\x00\x00\x00|\x00\x00d\x01\x00\x17S(\x02\x00\x00\x00Ni\x01\x00\x00\x00(\x00\x00\x00\x00(\x01\x00\x00\x00t\x01\x00\x00\x00n(\x00\x00\x00\x00(\x00\x00\x00\x00s\x1f\x00\x00\x00<ipython-input-25-e0be1c309720>t\x01\x00\x00\x00a\x01\x00\x00\x00s\x02\x00\x00\x00\x00\x01q\x02\x85q\x03Rq\x04c__builtin__\n__main__\nU\x01aq\x05NN}q\x06tq\x07Rq\x08.'
```

The traceback when we try and unpickle `a` in another process:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 289, in run
    sys.exit(self.workloop(pid=pid))
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 350, in workloop
    req = wait_for_job()
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 441, in receive
    ready, req = _receive(1.0)
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 413, in _recv
    return True, loads(get_payload())
  File "/usr/local/lib/python2.7/dist-packages/billiard/common.py", line 77, in pickle_loads
    return load(BytesIO(s))
AttributeError: 'module' object has no attribute '__main__'
```

**Comment by mmckerns** [comment]
I'm not seeing the error…
```
Python 2.7.9 (default, Dec 11 2014, 01:21:43) 
[GCC 4.2.1 Compatible Apple Clang 4.1 ((tags/Apple/clang-421.11.66))] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> def a(n):
...   return n+1
... 
>>> import dill
>>> dill.dumps(a)
'\x80\x02cdill.dill\n_create_function\nq\x00(cdill.dill\n_unmarshal\nq\x01U`c\x01\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00C\x00\x00\x00s\x08\x00\x00\x00|\x00\x00d\x01\x00\x17S(\x02\x00\x00\x00Ni\x01\x00\x00\x00(\x00\x00\x00\x00(\x01\x00\x00\x00t\x01\x00\x00\x00n(\x00\x00\x00\x00(\x00\x00\x00\x00s\x07\x00\x00\x00<stdin>t\x01\x00\x00\x00a\x01\x00\x00\x00s\x02\x00\x00\x00\x00\x01q\x02\x85q\x03Rq\x04c__builtin__\n__main__\nU\x01aq\x05NN}q\x06tq\x07Rq\x08.'
>>> 
```
and in the other process…
```
Python 2.7.9 (default, Dec 11 2014, 01:21:43) 
[GCC 4.2.1 Compatible Apple Clang 4.1 ((tags/Apple/clang-421.11.66))] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> x = '\x80\x02cdill.dill\n_create_function\nq\x00(cdill.dill\n_unmarshal\nq\x01U`c\x01\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00C\x00\x00\x00s\x08\x00\x00\x00|\x00\x00d\x01\x00\x17S(\x02\x00\x00\x00Ni\x01\x00\x00\x00(\x00\x00\x00\x00(\x01\x00\x00\x00t\x01\x00\x00\x00n(\x00\x00\x00\x00(\x00\x00\x00\x00s\x07\x00\x00\x00<stdin>t\x01\x00\x00\x00a\x01\x00\x00\x00s\x02\x00\x00\x00\x00\x01q\x02\x85q\x03Rq\x04c__builtin__\n__main__\nU\x01aq\x05NN}q\x06tq\x07Rq\x08.'
>>> f = dill.loads(x)
>>> f(1)
2
>>>
```

What's your version of `dill`, and how are you unpickling?

**Comment by maximilianr** [comment]
@mmckerns You're right. When I copy and paste that string into a new process, it works fine.

The error occurs when celery unpickles it on a worker. I'm fairly confident that we've successfully monkey patched in dill to celery (a lot more wouldn't work if we hadn't, including pickling & unpickling lambda functions defined in a module).

Unless anyone has any ideas, I'll hunt around some more and revert.

**Comment by mmckerns** [comment]
You mean this, right? https://github.com/celery/celery/issues/2526

If you just do `import dill`, that should bootstrap all of the `dill` types into the pickle registry.  (This was broken for the last few months, unbeknownst to me, but I just recently fixed it here: https://github.com/uqfoundation/dill/issues/107).  `dill` can inject types into the `pickle` registry, but not the `cPickle` registry.  The point being, if `celery` is calling `pickle.load`, it might not be calling a `dill` `Unpickler` (which is required in some cases) -- or if you are not doing an `import dill` and you are using `pickle` to unpickle, then you might also see failure.

**Comment by mmckerns** [comment]
I'm going to close this, but feel free to keep using this thread.

**Comment by maximilianr** [comment]
Great, thanks @mmckerns 

I'll try `import dill` (is that documented? We have been using dill extensively for a while and I haven't come across that?)
I'm also going to monkey patch a couple of other places in the celery library. I've put the full code below for reference; the final 7 lines are new. I'll add it to the issue above - that's our post & response - when it's tested. But the `import dill` solution is obviously much easier.

Appreciate the speedy and on-point response.
```python
def add_dill():
    import dill
    registry = kombu.serialization.registry
    kombu.serialization.pickle = dill

    registry.unregister('pickle')

    def pickle_loads(s, load=dill.load):
    # used to support buffer objects
        return load(BytesIO(s))

    def pickle_dumps(obj, dumper=dill.dumps):
        return dumper(obj, protocol=kombu.serialization.pickle_protocol)

    registry.register('pickle', pickle_dumps, pickle_loads,
                      content_type='application/x-python-serialize',
                      content_encoding='binary')

    # there are a couple of other places that celery uses pickle *without* referencing the registry, and imports
    # the module on init in a way that doesn't update if we change it in kombu.serialization; so we monkey patch
    # each one

    import celery.worker
    import celery.concurrency.asynpool
    celery.worker.state.pickle = dill
    celery.concurrency.asynpool._pickle = dill
```

**Comment by mmckerns** [comment]
documented… um… I thought it was somewhere more public… uh, I think so.

I know it's here:
https://github.com/uqfoundation/dill/blob/master/dill/__init__.py#L80
https://github.com/uqfoundation/dill/blob/master/dill/dill.py#L1125
