### ISSUE TITLE
pickle of zip fails after pickle of weakref with recurse=True

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/dill#119]
This is a very odd corner case… probably due to a reference to an inexact copy of weakref'ed object

```
Python 3.4.3 (default, May 25 2015, 18:57:37) 
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> dill.settings['recurse'] = True
>>> z = zip('0','1')
>>> dill.copy(z)
<zip object at 0x108852d88>
>>> 
>>> import weakref
>>> y = weakref.WeakValueDictionary()
>>> dill.copy(z)
<zip object at 0x108852cc8>
>>> x = weakref.WeakKeyDictionary()
>>> dill.copy(z)
<zip object at 0x108852c88>
>>> dill.copy(y)
<WeakValueDictionary at 4419886552>
>>> dill.copy(z)
(<class 'AttributeError'>, AttributeError("'module' object has no attribute 'iter'",), <traceback object at 0x10884f188>)
<function _get_attr at 0x107b48ae8> (<module 'weakref' from '/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/weakref.py'>, 'iter')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python3.4/site-packages/dill-0.2.4.dev0-py3.4.egg/dill/dill.py", line 159, in copy
    return loads(dumps(obj, *args, **kwds))
  File "/Users/mmckerns/lib/python3.4/site-packages/dill-0.2.4.dev0-py3.4.egg/dill/dill.py", line 209, in loads
    return load(file)
  File "/Users/mmckerns/lib/python3.4/site-packages/dill-0.2.4.dev0-py3.4.egg/dill/dill.py", line 199, in load
    obj = pik.load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 1038, in load
    dispatch[key[0]](self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 1384, in load_reduce
    value = func(*args)
  File "/Users/mmckerns/lib/python3.4/site-packages/dill-0.2.4.dev0-py3.4.egg/dill/dill.py", line 661, in _get_attr
    return getattr(self, name)
AttributeError: 'module' object has no attribute 'iter'
```
or
```
Python 3.4.3 (default, May 25 2015, 18:57:37) 
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import weakref
>>> import dill
>>> dill.settings['recurse'] = True
>>> 
>>> z = zip('0','1')
>>> dill.copy(z)
<zip object at 0x10bf90d88>
>>> x = weakref.WeakSet()          
>>> dill.copy(z)
<zip object at 0x10bf90e08>
>>> dill.copy(x)
<_weakrefset.WeakSet object at 0x10b0fc128>
>>> dill.copy(z)
(<class 'AttributeError'>, AttributeError("'module' object has no attribute 'iter'",), <traceback object at 0x10bf80348>)
<function _get_attr at 0x10b286ae8> (<module '_weakrefset' from '/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/_weakrefset.py'>, 'iter')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python3.4/site-packages/dill-0.2.4.dev0-py3.4.egg/dill/dill.py", line 159, in copy
    return loads(dumps(obj, *args, **kwds))
  File "/Users/mmckerns/lib/python3.4/site-packages/dill-0.2.4.dev0-py3.4.egg/dill/dill.py", line 209, in loads
    return load(file)
  File "/Users/mmckerns/lib/python3.4/site-packages/dill-0.2.4.dev0-py3.4.egg/dill/dill.py", line 199, in load
    obj = pik.load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 1038, in load
    dispatch[key[0]](self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 1384, in load_reduce
    value = func(*args)
  File "/Users/mmckerns/lib/python3.4/site-packages/dill-0.2.4.dev0-py3.4.egg/dill/dill.py", line 661, in _get_attr
    return getattr(self, name)
AttributeError: 'module' object has no attribute 'iter'
```

**Comment by mmckerns** [comment]
fixed by ffad7f6d833d04ad2eaae18f28277fafcfd210eb
