### ISSUE TITLE
test_classdef.py fails python25 with recurse=True

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/dill#121]
```
$ python test_classdef.py 
Traceback (most recent call last):
  File "test_classdef.py", line 116, in <module>
    assert dill.pickles(a1)
AssertionError
```

**Comment by mmckerns** [comment]
split off of #105

**Comment by mmckerns** [comment]
Looks like the issue is that `python2.6` and beyond have `numpy` pickle as `M2`, while `python2.5` pickles `numpy` as `M1` when `recurse=True` -- thus, `dill` tries to pickle all objects in `numpy`.

```
$ python test_classdef.py 
Nu: ((100,), float64)
F2: <function _create_array at 0x10bda8668>
B2: <built-in function _reconstruct>
T2: <class '__main__.TestArray'>
F2: <function _create_type at 0x10bda0ed8>
T1: <type 'type'>
F2: <function _load_type at 0x10bda0e60>
T4: <type 'numpy.ndarray'>
D2: <dict object at 0x7fd93b9e3660>
T4: <type 'staticmethod'>
F1: <function __getnewargs__ at 0x10bd6e848>
F2: <function _create_function at 0x10bda0f50>
Co: <code object __getnewargs__ at 0x10b62f558, file "test_classdef.py", line 112>
F2: <function _unmarshal at 0x10bda0de8>
D2: <dict object at 0x7fd93b9ed7e0>
M1: <module 'numpy' from '/Users/mmckerns/lib/python2.5/site-packages/numpy/__init__.pyc'>
F2: <function _import_module at 0x10bda8848>
D2: <dict object at 0x7fd93b9e0a90>
F2: <function disp at 0x10bc2d578>
F2: <function union1d at 0x10bc25938>
F2: <function all at 0x10bad6578>
F2: <function issubsctype at 0x10ba84230>
F2: <function savez at 0x10bc7ab90>
F2: <function atleast_2d at 0x10bafb2a8>
M1: <module 'numpy.matrixlib' from '/Users/mmckerns/lib/python2.5/site-packages/numpy/matrixlib/__init__.pyc'>
D2: <dict object at 0x7fd93b9e6990>
T4: <class 'numpy.matrixlib.defmatrix.matrix'>
T4: <class 'numpy.testing.nosetester.NoseTester'>
Me: <bound method NoseTester.bench of <numpy.testing.nosetester.NoseTester object at 0x10bc22ed0>>
T1: <type 'instancemethod'>
F1: <function bench at 0x10bab75f0>
Co: <code object bench at 0x10bab1f30, file "/Users/mmckerns/lib/python2.5/site-packages/numpy/testing/nosetester.py", line 382>
D2: <dict object at 0x7fd93b9d7780>
T4: <type 'exceptions.ImportError'>
M2: <module 'os' from '/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/os.pyc'>
F2: <function import_nose at 0x10bab71b8>
D2: <dict object at 0x7fd93b9f16b0>
D2: <dict object at 0x7fd93b923d20>
F2: <function bmat at 0x10bc349b0>
M1: <module 'numpy.matrixlib.defmatrix' from '/Users/mmckerns/lib/python2.5/site-packages/numpy/matrixlib/defmatrix.pyc'>
D2: <dict object at 0x7fd93b9e18f0>
B2: <built-in function concatenate>
F2: <function asmatrix at 0x10bc31938>
F2: <function matrix_power at 0x10bc319b0>
M1: <module 'numpy.core.numeric' from '/Users/mmckerns/lib/python2.5/site-packages/numpy/core/numeric.pyc'>
D2: <dict object at 0x7fd93b9de2c0>
T4: <type 'numpy.float128'>
D2: <dict object at 0x7fd93a4dfb10>
T4: <type 'numpy.bool_'>
T4: <type 'numpy.int8'>
T4: <type 'numpy.uint8'>
T4: <type 'numpy.int16'>
T4: <type 'numpy.uint16'>
T4: <type 'numpy.int32'>
T4: <type 'numpy.uint32'>
T4: <type 'numpy.int64'>
T4: <type 'numpy.uint64'>
T4: <type 'numpy.int64'>
Traceback (most recent call last):
  File "test_classdef.py", line 117, in <module>
    assert dill.pickles(a1)
AssertionError
```

**Comment by mmckerns** [comment]
Distilling to the simplest possible case:
```
Python 2.7.10 (default, May 25 2015, 13:16:30) 
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import dill
>>> dill.dumps(numpy)
'\x80\x02cdill.dill\n_import_module\nq\x00U\x05numpyq\x01\x85q\x02Rq\x03.'
>>> 
```
and
```
Python 2.5.6 (r256:88840, Nov 18 2012, 05:37:10) 
[GCC 4.2.1 Compatible Apple Clang 4.1 ((tags/Apple/clang-421.11.66))] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Module readline not available.
>>> import numpy
>>> import dill
>>> dill.dumps(numpy)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python2.5/site-packages/dill-0.2.4.dev0-py2.5.egg/dill/dill.py", line 192, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/Users/mmckerns/lib/python2.5/site-packages/dill-0.2.4.dev0-py2.5.egg/dill/dill.py", line 186, in dump
    pik.dump(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 224, in dump
    self.save(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python2.5/site-packages/dill-0.2.4.dev0-py2.5.egg/dill/dill.py", line 1057, in save_module
    state=_main_dict)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 419, in save_reduce
    save(state)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python2.5/site-packages/dill-0.2.4.dev0-py2.5.egg/dill/dill.py", line 748, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 681, in _batch_setitems
    save(v)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python2.5/site-packages/dill-0.2.4.dev0-py2.5.egg/dill/dill.py", line 1057, in save_module
    state=_main_dict)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 419, in save_reduce
    save(state)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python2.5/site-packages/dill-0.2.4.dev0-py2.5.egg/dill/dill.py", line 748, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 681, in _batch_setitems
    save(v)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python2.5/site-packages/dill-0.2.4.dev0-py2.5.egg/dill/dill.py", line 1057, in save_module
    state=_main_dict)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 419, in save_reduce
    save(state)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python2.5/site-packages/dill-0.2.4.dev0-py2.5.egg/dill/dill.py", line 748, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 681, in _batch_setitems
    save(v)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python2.5/site-packages/dill-0.2.4.dev0-py2.5.egg/dill/dill.py", line 1057, in save_module
    state=_main_dict)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 419, in save_reduce
    save(state)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python2.5/site-packages/dill-0.2.4.dev0-py2.5.egg/dill/dill.py", line 748, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 681, in _batch_setitems
    save(v)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python2.5/site-packages/dill-0.2.4.dev0-py2.5.egg/dill/dill.py", line 748, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 681, in _batch_setitems
    save(v)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python2.5/site-packages/dill-0.2.4.dev0-py2.5.egg/dill/dill.py", line 1101, in save_type
    StockPickler.save_global(pickler, obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/pickle.py", line 753, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <type 'numpy.int64'>: it's not the same object as numpy.int64
```

**Comment by mmckerns** [comment]
The root of the issue is this:
```
        if hasattr(obj, "__file__"):
            names = ["base_prefix", "base_exec_prefix", "exec_prefix",
                     "prefix", "real_prefix"]
            builtin_mod = any([obj.__file__.startswith(getattr(sys, name))
                           for name in names if hasattr(sys, name)])
        else:
            builtin_mod = True
        if obj.__name__ not in ("builtins", "dill") \
           and not builtin_mod or is_dill(pickler) and obj is pickler._main:
            log.info("M1: %s" % obj)
            _main_dict = obj.__dict__.copy() #XXX: better no copy? option to copy?
            [_main_dict.pop(item, None) for item in singletontypes
                + ["__builtins__", "__loader__"]]
            pickler.save_reduce(_import_module, (obj.__name__,), obj=obj,
                                state=_main_dict)
        else:
            log.info("M2: %s" % obj)
            pickler.save_reduce(_import_module, (obj.__name__,), obj=obj)
```

@matsjoyce: is there any reason to test for `sys.prefix` (and similar) instead of testing for `site-packages` in `obj.__file__`?   If `site-packages` in `obj.__file__`, then we have an installed module.

**Comment by mmckerns** [comment]
"fixed" in 49556c5875fc7e5300aeb5cf61b84e379e321067.  It's still kind of a hack.

**Comment by matsjoyce** [comment]
Well, on my system, `site-packages` is under `sys.prefix`, and as `sys.prefix` is more "official", I used that. It works on python 2.6-7, so I guess python 2.5 was different. I haven't got any python 2.5 installations, so I can't really say.

**Comment by mmckerns** [comment]
I have a split install, where python itself is from macports… and any code installed via macports gets installed in the corresponding `site-packages` -- however, I also maintain a separate install directory for packages under development in my home directory (i.e. `~/lib/python2.7/site-packages`).  This is completely missed by `sys.prefix` regardless of the version of python.  However, `obj.__file__` gets it right, as it's specific to the installed module as opposed to the path of `sys.executable`.
