### ISSUE TITLE
uninitialized classmethod object

### ISSUE THREAD

**Issue by hyukim17** [uqfoundation/dill#124]
I have a very simple classmethod example that fails to pickle with dill. Code is below.

```
import dill

class A(object):
  @classmethod
  def test(cls):
    pass


a = A()

res = dill.dumps(a)
new_obj = dill.loads(res)

new_obj.__class__.test()
```

**Comment by matsjoyce** [comment]
Exception:
```pytb
Traceback (most recent call last):
  File "a.py", line 14, in <module>
    new_obj.__class__.test()
RuntimeError: uninitialized classmethod object
```

You can get the same error by:
```py
>>> class A: pass
... 
>>> A.test = classmethod.__new__(classmethod)
>>> A.test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: uninitialized classmethod object
```

Possible fix:
```py
import dill
dill.dill._trace(1)

@dill.register(classmethod)
def save_classmethod(pickler, obj):
    pickler.save_reduce(classmethod, (obj.__func__,), obj=obj)

class A(object):
  @classmethod
  def test(cls):
    pass


a = A()

res = dill.dumps(a)
new_obj = dill.loads(res)
new_obj.__class__.test()
```

Before `dill` just attempted to pickle the `__dict__`, which is empty. It also fails for `staticmethod`s, so should we add:
```py
@register(classmethod)
@register(staticmethod)
def save_classmethod(pickler, obj):
    log.info("Cm: %s" % obj)
    pickler.save_reduce(type(obj), (obj.__func__,), obj=obj)
```
@mmckerns?

Proof of workingness:

```py
import dill
dill.dill._trace(1)

@dill.register(classmethod)
@dill.register(staticmethod)
def save_classmethod(pickler, obj):
    pickler.save_reduce(type(obj), (obj.__func__,), obj=obj)

class A(object):
  @staticmethod
  def test_sm():
    pass
  @classmethod
  def test_cm(cls):
    pass


a = A()

res = dill.dumps(a)
new_obj = dill.loads(res)
new_obj.__class__.test_sm()
new_obj.__class__.test_cm()
```

Output:
```py
T2: <class '__main__.A'>
F2: <function _create_type at 0x7fc4cdb389b0>
T1: <type 'type'>
F2: <function _load_type at 0x7fc4cdb38938>
T1: <type 'object'>
D2: <dict object at 0x7fc4cdad8b40>
Cm: <classmethod object at 0x7fc4cd884248>
T4: <type 'classmethod'>
F1: <function test_cm at 0x7fc4cd8891b8>
F2: <function _create_function at 0x7fc4cdb38a28>
Co: <code object test_cm at 0x7fc4d4939f30, file "a.py", line 14>
F2: <function _unmarshal at 0x7fc4cdb388c0>
D1: <dict object at 0x7fc4d49d5168>
D2: <dict object at 0x7fc4cdad8c58>
Cm: <staticmethod object at 0x7fc4cd884280>
T4: <type 'staticmethod'>
F1: <function test_sm at 0x7fc4cd8890c8>
Co: <code object test_sm at 0x7fc4d4939db0, file "a.py", line 11>
D1: <dict object at 0x7fc4d49d5168>
D2: <dict object at 0x7fc4cdad2a28>
D2: <dict object at 0x7fc4cdae67f8>
```
Works in python 3.4 and 2.7.

**Comment by mmckerns** [comment]
Looks like a good addition to me.

**Comment by matsjoyce** [comment]
OK, PRed it.

**Comment by mmckerns** [comment]
Thanks.  looks good.  I added 2.5 support for the hell of it.

**Comment by matsjoyce** [comment]
Ah, thought I got the backwards compat with the 2.6 fix. Maybe its time to install a few more python versions somehow. Bit hard on ArchLinux, though.

**Comment by mmckerns** [comment]
I need to reassess whether `2.5` (and `3.x` <=  `3.2`) still need to be supported.  I did because there were still large systems in production using those versions as the system python version.  Terrible.
