### ISSUE TITLE
RecursionError using recurse=True when class method refers to class attribute

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/dill#129]
```
>>> import dill
>>> 
>>> class Foo:
...     y = 1
...     def bar( self, x ):
...         return x + Foo.y
... 
>>> f = Foo()
>>> 
>>> dill.dumps(f, byref=False, recurse=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python3.4/site-packages/dill-0.2.5.dev0-py3.4.egg/dill/dill.py", line 192, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/Users/mmckerns/lib/python3.4/site-packages/dill-0.2.5.dev0-py3.4.egg/dill/dill.py", line 186, in dump
    pik.dump(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 412, in dump
    self.save(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 524, in save
    self.save_reduce(obj=obj, *rv)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 598, in save_reduce
    save(cls)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python3.4/site-packages/dill-0.2.5.dev0-py3.4.egg/dill/dill.py", line 1096, in save_type
    obj.__bases__, _dict), obj=obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 603, in save_reduce
    save(args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 744, in save_tuple
    save(element)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self

…

  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 713, in save_str
    self.memoize(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pickle.py", line 435, in memoize
    self.write(self.put(idx))
RuntimeError: maximum recursion depth exceeded
```

**Comment by mmckerns** [comment]
Also see: #128

**Comment by mmckerns** [comment]
For example: in file `foo.py`:
```
# foo.py
class Foo:
  y = 1
  def bar(self, x):
    return x + Foo.y
```
We then try to serialize...
```
>>> import foo
>>> import dill
>>> dill.settings['recurse'] = True
>>> dill.detect.trace(True)
>>> f = foo.Foo()
>>> 
>>> dill.detect.errors(f.bar)
Me: <bound method Foo.bar of <foo.Foo instance at 0x10221d638>>
T1: <type 'instancemethod'>
F2: <function _load_type at 0x1021fa668>
F1: <function bar at 0x101266320>
F2: <function _create_function at 0x1021fa758>
Co: <code object bar at 0x10143cf30, file "foo.py", line 3>
F2: <function _unmarshal at 0x1021fa5f0>
D2: <dict object at 0x1022247f8>
C2: foo.Foo
D2: <dict object at 0x102217c58>
D2: <dict object at 0x10122a4b0>
>>>
>>> dill.detect.globalvars(f.bar)
{'Foo': <class foo.Foo at 0x101436d50>}
>>> 
>>> class Bar:
...   y = 1
...   def foo(self, x):
...     return x + Bar.y
... 
>>> b = Bar()
>>> dill.detect.globalvars(b.foo)
{'Bar': <class __main__.Bar at 0x102257600>}
>>> dill.detect.errors(b.foo)
Me: <bound method Bar.foo of <__main__.Bar instance at 0x10221d758>>
T1: <type 'instancemethod'>
F2: <function _load_type at 0x1021fa668>
F1: <function foo at 0x10225b8c0>
F2: <function _create_function at 0x1021fa758>
Co: <code object foo at 0x1012720b0, file "<stdin>", line 3>
F2: <function _unmarshal at 0x1021fa5f0>
D2: <dict object at 0x102224280>
C1: __main__.Bar
T1: <type 'classobj'>
D2: <dict object at 0x10221e398>
F1: <function foo at 0x10225b8c0>
D2: <dict object at 0x1022244b0>
C1: __main__.Bar
D2: <dict object at 0x102219398>
AssertionError()
>>> 
```

The serialization blows up due to the class `__main__.Bar` appearing as the `globalvars` in `F1` function `foo`.

Turning off `recurse` works.
```
>>> dill.settings['recurse']=False
>>> dill.detect.errors(b.foo)
Me: <bound method Bar.foo of <__main__.Bar instance at 0x10221d758>>
T1: <type 'instancemethod'>
F2: <function _load_type at 0x1021fa668>
F1: <function foo at 0x10225b8c0>
F2: <function _create_function at 0x1021fa758>
Co: <code object foo at 0x1012720b0, file "<stdin>", line 3>
F2: <function _unmarshal at 0x1021fa5f0>
D1: <dict object at 0x101185168>
D2: <dict object at 0x102219398>
C1: __main__.Bar
T1: <type 'classobj'>
D2: <dict object at 0x10221e398>
D2: <dict object at 0x1022175c8>
>>> dill.detect.errors(f.bar)
Me: <bound method Foo.bar of <foo.Foo instance at 0x10221d638>>
T1: <type 'instancemethod'>
F2: <function _load_type at 0x1021fa668>
F1: <function bar at 0x101266320>
F2: <function _create_function at 0x1021fa758>
Co: <code object bar at 0x10143cf30, file "foo.py", line 3>
F2: <function _unmarshal at 0x1021fa5f0>
D4: <dict object at 0x1012786e0>
D2: <dict object at 0x102217c58>
C2: foo.Foo
D2: <dict object at 0x10122a4b0>
```

So potentially, `dill` might turn off `recurse` when a method of the class references it's class definition and the class is defined in `__main__`... or possibly it should just pop it from the `globalvars`.

**Comment by mmckerns** [comment]
The issue, upon closer inspection, seems to stem from a request to store the `__dict__` a function (`F1`) which is already on the pickle trace.

**Comment by jetheron** [comment]
Similar error for function with a static variable (aka, closure).
For example,
```python
import dill
def foo():
    def _foo():
        if not hasattr(_foo, '_counter'):
            _foo._counter = 0
        _foo._counter += 1
        return _foo._counter
    return _foo
f = foo()
f()
f()
dill.dumps(f)
```

**Comment by mmckerns** [comment]
I'm closing this, as it appears to work as of the patch applied for #75.
@jetheron: It does not fix your code, however.  I'm going to open that as a new ticket.
