### ISSUE TITLE
Different bytes dumped for python types

### ISSUE THREAD

**Issue by simonzack** [uqfoundation/dill#142]
In order to maintain the same hashes in joblib's argument hasher when switching to dill, objects which can be pickled by pickle should return the same bytes. This is currently not the case for types themselves, e.g. `ValueError`:

    >>> dill.dumps(ValueError)
    b'\x80\x03cdill.dill\n_load_type\nq\x00X\n\x00\x00\x00ValueErrorq\x01\x85q\x02Rq\x03.'
    >>> pickle.dumps(ValueError)
    b'\x80\x03cbuiltins\nValueError\nq\x00.'

**Comment by matsjoyce** [comment]
I don't think that's an option for quite a lot of objects, as dill pickles them differently in order to give more functionality than pickle, e.g. `__main__` classes.

**Comment by mmckerns** [comment]
@simonzack: `pickle` is serializing by reference.  `dill` is not, by default.  You might get what you want if you use `dumps` with `byref=True` -- or use `dill.settings['byref']=True`.

**Comment by mmckerns** [comment]
@simonzack: any updates on this?  It's really out of scope for `dill`.  In `python2.x` a `ValueError` returns the same thing, but in `3.x` it doesn't.  I checked, and `byref` has no effect.

Can you detail what you see as different here, and hopefully it's minimal... so it might fit within the `byref` setting (which has a much more `pickle`-like behavior).

**Comment by simonzack** [comment]
@mmckerns Sorry for the delay, I'm not sure if I'm doing it correctly, but this patch makes it work, if that makes any sense.

    https://github.com/simonzack/joblib/commit/f79d276fa9f875c6bcd16379ab45e981b33ed8bb

**Comment by mmckerns** [comment]
Hmm… ok, that's simple, and an interesting change.  I'll run it through the test suite and timer, and if it doesn't seem to have any adverse effects, I'll take the patch.  Would you want to submit a PR or (if `dill` is to accept the patch) you ok with me just applying it?

**Comment by mmckerns** [comment]
@simonzack: All `dill` tests pass if you also pop three key types from `_builtin_typemap`.  If this passes your tests, then the change seems like it'd be fine to go into `dill`.   Also I noticed there's a change to the `CodeType` that you made, can you explain this in this or another thread.  I'd prefer you PR any changes you want to see in `dill`… but I can apply the patch that I've submitted to you as a PR this first time, if everything checks out on your end.  @matsjoyce: you may want to grab the `dill.py` from the above-referenced PR, and kick the tires a bit… (and potentially, the slight edit to` CodeType` that @simonzack has).

**Comment by matsjoyce** [comment]
So in all, this is the changes (I pruned it a bit, because #144 hasn't be merged into @simonzack version):

```diff
--- GitHub/dill/dill/dill.py    2015-12-26 15:33:58.777320272 +0000
+++ dill.py     2015-12-26 15:31:07.633858294 +0000
@@ -492,8 +492,11 @@
     _reverse_typemap['OutputType'] = OutputType
 if PY3:
     _typemap = dict((v, k) for k, v in _reverse_typemap.items())
+    _builtin_typemap = dict((v, k) for k, v in dict(_create_typemap()).items())
 else:
     _typemap = dict((v, k) for k, v in _reverse_typemap.iteritems())
+    _builtin_typemap = dict((v, k) for k, v in dict(_create_typemap()).iteritems())
+del _builtin_typemap[CodeType]
+del _builtin_typemap[ClassType]
+del _builtin_typemap[MethodType]
+_builtin_typemap.pop(TypeType, None)
+_builtin_typemap.pop(type(None), None)
 
 def _unmarshal(string):
     return marshal.loads(string)
@@ -756,14 +759,14 @@
         args = (
             obj.co_argcount, obj.co_kwonlyargcount, obj.co_nlocals,
             obj.co_stacksize, obj.co_flags, obj.co_code, obj.co_consts,
-            obj.co_names, obj.co_varnames, obj.co_filename, obj.co_name,
-            obj.co_firstlineno, obj.co_lnotab, obj.co_freevars, obj.co_cellvars
+            obj.co_names, obj.co_varnames, '', obj.co_name,
+            0, b'', obj.co_freevars, obj.co_cellvars
         )
     else:
         args = (
             obj.co_argcount, obj.co_nlocals, obj.co_stacksize, obj.co_flags,
             obj.co_code, obj.co_consts, obj.co_names, obj.co_varnames,
-            obj.co_filename, obj.co_name, obj.co_firstlineno, obj.co_lnotab,
+            '', obj.co_name, 0, b'',
             obj.co_freevars, obj.co_cellvars
         )
     pickler.save_reduce(CodeType, args, obj=obj)
@@ -1181,7 +1184,9 @@
 @register(TypeType)
 def save_type(pickler, obj):
    #stack.add(obj) #XXX: probably don't need object from all cases below
-    if obj in _typemap:
+    if obj in _builtin_typemap:
+        log.info("T0: %s" % obj)
+        StockPickler.save_global(pickler, obj)
+        log.info("# T0")
+    elif obj in _typemap:
         log.info("T1: %s" % obj)
         pickler.save_reduce(_load_type, (_typemap[obj],), obj=obj)
         log.info("# T1")
@@ -1323,4 +1328,4 @@
```

Using
```py3
>>> p=dill.Pickler(io.BytesIO())                    
>>> for i in set(dill.dill._builtin_typemap.keys()):
...  try: p.save_global(i)                          
...  except Exception as e: print(i, e)                            
... 
<class 'frame'> Can't pickle <class 'frame'>: it's not found as builtins.frame
<class 'mappingproxy'> Can't pickle <class 'mappingproxy'>: it's not found as builtins.mappingproxy
<class 'getset_descriptor'> Can't pickle <class 'getset_descriptor'>: it's not found as builtins.getset_descriptor
<class 'member_descriptor'> Can't pickle <class 'member_descriptor'>: it's not found as builtins.member_descriptor
<class 'coroutine'> Can't pickle <class 'coroutine'>: it's not found as builtins.coroutine
<class 'generator'> Can't pickle <class 'generator'>: it's not found as builtins.generator
<class 'function'> Can't pickle <class 'function'>: it's not found as builtins.function
<class 'traceback'> Can't pickle <class 'traceback'>: it's not found as builtins.traceback
<class 'builtin_function_or_method'> Can't pickle <class 'builtin_function_or_method'>: it's not found as builtins.builtin_function_or_method
<class 'module'> Can't pickle <class 'module'>: it's not found as builtins.module
```
shows that some more types would have to be removed, as `Pickler.save_global` can't handle them. In the current PR, only code and method is removed. You can reach these types by doing things like:

```py3
>>> class A:pass
...
>>> dill.dumps(A.__dict__.__class__)
Traceback (most recent call last):
  File "/usr/lib/python3.5/pickle.py", line 268, in _getattribute
    obj = getattr(obj, subpath)
AttributeError: module 'builtins' has no attribute 'mappingproxy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/pickle.py", line 907, in save_global
    obj2, parent = _getattribute(module, name)
  File "/usr/lib/python3.5/pickle.py", line 271, in _getattribute
    .format(name, obj))
AttributeError: Can't get attribute 'mappingproxy' on <module 'builtins' (built-in)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matthew/dill/dill.py", line 242, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/home/matthew/dill/dill.py", line 235, in dump
    pik.dump(obj)
  File "/usr/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/matthew/dill/dill.py", line 1192, in save_type
    StockPickler.save_global(pickler, obj)
  File "/usr/lib/python3.5/pickle.py", line 911, in save_global
    (obj, module_name, name))
_pickle.PicklingError: Can't pickle <class 'mappingproxy'>: it's not found as builtins.mappingproxy
```

Currently dill can handle this:

```py3
>>> class A: pass
... 
>>> dill.dumps(A.__dict__.__class__)
b'\x80\x03cdill.dill\n_load_type\nq\x00X\x10\x00\x00\x00MappingProxyTypeq\x01\x85q\x02Rq\x03.'
```

I can't see that anything else would break, though. The changes to `save_code` seem to be removing info, so I don't think that should be included. Also `_builtin_typemap` could be a set or list, as a dictionary isn't really needed.

**Comment by mmckerns** [comment]
@matsjoyce: yeah, I also don't understand the need to remove information in `save_code`.  So when I did a quick check of all the `dill` tests, I didn't include the changes to `save_code`, but did make the other changes you presented above (and are in the PR).

I'm not actually sure you are correct about the `BuiltinMethodType`, `ModuleType`, and so on.  I had those originally, and then removed them.  The set I included were the minimal one I could find that enabled all existing `dill` tests to pass… so what I would expect happens for say a `BuiltinModuleType` is that it fails in the `StockPickler` due to a dependency failing… so it actually would now pass (and indeed I see that as the case).  I didn't, however, do testing in the interpreter… which works slightly differently, as you note -- and `dill` should not lose any functionality for working interactively.

So, for this to go forward, a solution would be needed that works for the interpreter as well as from a file.  I think that the most efficient route @simonzack can take is to provide us with whatever he's testing against for `joblib` that demonstrates his needs.  Then we can find if they are incompatible or not.

Also, agreed about `_builtin_typemap` being able to be a set.

**Comment by simonzack** [comment]
Sorry about the delay, I did indeed remove the line number, column number, and path of `save_code`, since this affected the caching of lambda functions. For example, say I cache a class with a parameter being lambda:

    from joblib import Memory
    mem = Memory(cachedir=cachedir)

    @mem.cache
    def f(arguments):
        pass

    f(lambda: 1)

This works, but if I add a comment somewhere


    from joblib import Memory
    mem = Memory(cachedir=cachedir)

    @mem.cache
    def f(arguments):
        pass

    # does nothing
    f(lambda: 1)

Then the old cache is suddenly invalidated which makes no sense. The path issue is similar, in that if the project moves from one server to another then the cache is also invalidated. Computing the cache can be rather expensive for things like neural nets.

If this patch is unacceptable perhaps there could be a flag to enable this behavior as a compromise?

I can definitely send the PR for the typemap patch, I'll run some joblib tests to see if the new code works.

**Comment by mmckerns** [comment]
@simonzack: a setting for this and your other needed caching behavior is a possibility, and probably the best option I can give you.  Let me know exactly what other behavior you need.

For me, I think the real problem is having a `joblib` requirement that `dill` pickles have to exactly match ones from `pickle`.  I have built a caching module (`klepto`) that's more generic than `joblib`, and with it you can pick your hasher for the cache, copy the cache easily, and/or switch to a new hasher.  So, if you had an existing cache, then you could read it with a `pickle` hasher, and write it with a `dill` hasher.

Anyway, I haven't noticed cases where the cache is invalidated in `klepto`, with code change as in your example… but I'll have to confirm that.  Anyway, if you detail what you need, I can look at putting it into a setting called `dill.settings['caching']` or something like that.

**Comment by mmckerns** [comment]
With a quick check… I don't see the problem you are reporting when I am using `klepto`… so it must just be how `joblib` is hashing it's cache.

```
>>> import klepto as k
>>> import dill
>>> @k.inf_cache(keymap=k.keymaps.picklemap(serializer=dill))
... def f(args):
...   pass
... 
>>> f(lambda: 1)
>>> s = f.__cache__().keys()[0]
>>> f(lambda: 1) # comment
>>> s in f.__cache__().keys()
True
>>> len(f.__cache__())
1
```

**Comment by mmckerns** [comment]
@simonzack:  Aha… if you have the `lambda` function defined in a file, and you edit the file (to add a comment, or something like that)… then I see a change in the line number in the `dill` pickle.  Thus, you would have a different cache key.  So, I see your case above in `klepto` as well.  I expect it's a really rare corner case, but nonetheless, it's odd to have adding a comment affect the pickle of a lambda.
