### ISSUE TITLE
dump_session fails if there are closed files

### ISSUE THREAD

**Issue by Aerospace2015** [uqfoundation/dill#143]
dump_session fails if there are closed files:

    Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from math import sqrt
    >>> with open("sqrt.txt", "w") as f:
    ...     for i in range(13):
    ...         f.write("%2d %18.16f\n" % (i, sqrt(i)))
    ...
    >>> import dill
    >>> save = dill.dump_session
    >>> save('sqrt.pkl')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "c:\python27\lib\site-packages\dill\dill.py", line 282, in dump_session
        pickler.dump(main)
      File "c:\python27\lib\pickle.py", line 224, in dump
        self.save(obj)
      File "c:\python27\lib\pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
      File "c:\python27\lib\site-packages\dill\dill.py", line 1058, in save_module
        state=_main_dict)
      File "c:\python27\lib\pickle.py", line 425, in save_reduce
        save(state)
      File "c:\python27\lib\pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
      File "c:\python27\lib\site-packages\dill\dill.py", line 748, in save_module_dict
        StockPickler.save_dict(pickler, obj)
      File "c:\python27\lib\pickle.py", line 655, in save_dict
        self._batch_setitems(obj.iteritems())
      File "c:\python27\lib\pickle.py", line 687, in _batch_setitems
        save(v)
      File "c:\python27\lib\pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
      File "c:\python27\lib\site-packages\dill\dill.py", line 820, in save_file
        return _save_file(pickler, obj, open)
      File "c:\python27\lib\site-packages\dill\dill.py", line 787, in _save_file
        obj.flush()
    ValueError: I/O operation on closed file
    >>> del f
    >>> save('sqrt.pkl')
    >>>

**Comment by matsjoyce** [comment]
Could you see if #144 fixes this?

**Comment by Aerospace2015** [comment]
Yes, that fixed it  (I manually edited dill.py and deleted dill.pyc.)
Thanks for you quick response!

**Comment by mmckerns** [comment]
confirmed fixed, so am closing this.
