### ISSUE TITLE
AssertionError with trying to use dill on astropy compound model

### ISSUE THREAD

**Issue by Lyalpha** [uqfoundation/dill#170]
I am using [`astropy`'s compound models](http://docs.astropy.org/en/stable/modeling/compound-models.html) (i.e. `g2` below) and attempting to pickle them with `dill`.

The python `pickle` module appears to pickle them successfully however `dill` gives an `AssertionError`:

    from cStringIO import StringIO
    #import cPickle as pickle     -> works with this line instead of dill
    import dill as pickle
    from astropy.modeling import models

    s = StringIO()
    g1 =  models.Gaussian1D()
    pickle.dump(g1,s)
    g2 =  models.Gaussian1D() + models.Gaussian1D()
    pickle.dump(g2, s)

```
Traceback (most recent call last):
    pickle.dump(g2, s)
  File "/usr/lib/python2.7/site-packages/dill/dill.py", line 236, in dump
    pik.dump(obj)
  File "/usr/lib64/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib64/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib64/python2.7/pickle.py", line 396, in save_reduce
    save(cls)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/site-packages/dill/dill.py", line 1216, in save_type
    obj.__bases__, _dict), obj=obj)
  File "/usr/lib64/python2.7/pickle.py", line 401, in save_reduce
    save(args)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 562, in save_tuple
    save(element)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/site-packages/dill/dill.py", line 835, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib64/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib64/python2.7/pickle.py", line 681, in _batch_setitems
    save(v)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/site-packages/dill/dill.py", line 798, in save_function
    obj.__dict__), obj=obj)
  File "/usr/lib64/python2.7/pickle.py", line 405, in save_reduce
    self.memoize(obj)
  File "/usr/lib64/python2.7/pickle.py", line 244, in memoize
    assert id(obj) not in self.memo
AssertionError
```

I guess this may need knowledge from the `astropy` side, but since it worked with vanilla `pickle` I thought I'd try here. The end game is using `lambda` functions within these models and so I need to use `dill` to serialize them.

`python 2.7.5`
`dill 0.2.5`
`astropy 1.1.2`

**Comment by matsjoyce** [comment]
Using the dev version of dill, this works fine! Could you add `pickle.dill._trace(1)` after you imports, and post the resulting output here? Thanks. My output is:
```
T4: <class 'astropy.modeling.functional_models.Gaussian1D'>
Name: Gaussian1D
Inputs: (u'x',)
Outputs: (u'y',)
Fittable parameters: ('amplitude', 'mean', 'stddev')
# T4
D2: <dict object at 0x7fa262b4fb40>
B2: <built-in function _reconstruct>
# B2
T4: <type 'numpy.ndarray'>
# T4
T4: <type 'numpy.dtype'>
# T4
D2: <dict object at 0x7fa262b4fc58>
D2: <dict object at 0x7fa262b4fe88>
# D2
D2: <dict object at 0x7fa262b51168>
# D2
D2: <dict object at 0x7fa262b4fd70>
# D2
# D2
T4: <type 'collections.defaultdict'>
# T4
T1: <type 'dict'>
F2: <function _load_type at 0x7fa26cc41578>
# F2
# T1
D2: <dict object at 0x7fa262b516e0>
Sl: slice(2, 3, None)
T1: <type 'slice'>
# T1
# Sl
# D2
D2: <dict object at 0x7fa262b514b0>
Sl: slice(0, 1, None)
# Sl
# D2
D2: <dict object at 0x7fa262b515c8>
Sl: slice(1, 2, None)
# Sl
# D2
# D2
T2: <class '__main__.CompoundModel0'>
Name: CompoundModel0
Inputs: (u'x',)
Outputs: (u'y',)
Fittable parameters: (u'amplitude_0', u'mean_0', u'stddev_0', u'amplitude_1', u'mean_1', u'stddev_1')
Expression: [0] + [1]
Components: 
    [0]: <Gaussian1D(amplitude=1.0, mean=0.0, stddev=1.0)>

    [1]: <Gaussian1D(amplitude=1.0, mean=0.0, stddev=1.0)>
F2: <function _create_type at 0x7fa26cc415f0>
# F2
T4: <class 'astropy.modeling.core._CompoundModelMeta'>
# T4
T4: <class 'astropy.modeling.core._CompoundModel'>
# T4
D2: <dict object at 0x7fa262b5b4b0>
T4: <class 'astropy.modeling.functional_models.Gaussian1D'>
Name: Gaussian1D
Inputs: (u'x',)
Outputs: (u'y',)
Fittable parameters: ('amplitude', 'mean', 'stddev')
# T4
D2: <dict object at 0x7fa262b51050>
B2: <built-in function _reconstruct>
# B2
T4: <type 'numpy.ndarray'>
# T4
T4: <type 'numpy.dtype'>
# T4
D2: <dict object at 0x7fa262b517f8>
D2: <dict object at 0x7fa262b51a28>
# D2
D2: <dict object at 0x7fa262b51c58>
# D2
D2: <dict object at 0x7fa262b51910>
# D2
# D2
T4: <type 'collections.defaultdict'>
# T4
T1: <type 'dict'>
F2: <function _load_type at 0x7fa26cc41578>
# F2
# T1
D2: <dict object at 0x7fa262b59280>
Sl: slice(2, 3, None)
T1: <type 'slice'>
# T1
# Sl
# D2
D2: <dict object at 0x7fa262b59050>
Sl: slice(0, 1, None)
# Sl
# D2
D2: <dict object at 0x7fa262b59168>
Sl: slice(1, 2, None)
# Sl
# D2
# D2
D2: <dict object at 0x7fa262b51e88>
D2: <dict object at 0x7fa262b51d70>
D2: <dict object at 0x7fa262b59398>
# D2
D2: <dict object at 0x7fa262b595c8>
# D2
D2: <dict object at 0x7fa262b51b40>
# D2
# D2
D2: <dict object at 0x7fa262b59b40>
Sl: slice(2, 3, None)
# Sl
# D2
D2: <dict object at 0x7fa262b59910>
Sl: slice(0, 1, None)
# Sl
# D2
D2: <dict object at 0x7fa262b59a28>
Sl: slice(1, 2, None)
# Sl
# D2
# D2
T4: <class 'astropy.modeling.parameters.Parameter'>
# T4
D2: <dict object at 0x7fa262b5a398>
B2: <built-in function scalar>
# B2
# D2
D2: <dict object at 0x7fa262b5a280>
# D2
D2: <dict object at 0x7fa262b5b280>
# D2
T4: <class 'astropy.modeling.utils.ExpressionTree'>
# T4
D2: <dict object at 0x7fa262b5f168>
D2: <dict object at 0x7fa262b5f280>
# D2
D2: <dict object at 0x7fa262b5f398>
# D2
# D2
D2: <dict object at 0x7fa262b5a5c8>
# D2
D2: <dict object at 0x7fa262b5a4b0>
# D2
D2: <dict object at 0x7fa262b596e0>
# D2
T4: <class '_weakrefset.WeakSet'>
# T4
D2: <dict object at 0x7fa262b4fa28>
F1: <function _remove at 0x7fa262bcd5f0>
F2: <function _create_function at 0x7fa26cc41668>
# F2
Co: <code object _remove at 0x7fa26e57beb0, file "/usr/lib/python2.7/_weakrefset.py", line 38>
T1: <type 'code'>
# T1
# Co
D4: <dict object at 0x7fa26e566a28>
# D4
R1: <weakref at 0x7fa262bce520; to 'WeakSet' at 0x7fa262bcbad0>
F2: <function _create_weakref at 0x7fa26cc41b90>
# F2
# R1
D2: <dict object at 0x7fa262b5a910>
# D2
# F1
T4: <type 'set'>
# T4
# D2
D2: <dict object at 0x7fa262b4f910>
F1: <function _remove at 0x7fa262bb99b0>
D4: <dict object at 0x7fa26e566a28>
# D4
R1: <weakref at 0x7fa262bce4c8; to 'WeakSet' at 0x7fa262bcbb50>
# R1
D2: <dict object at 0x7fa262b5aa28>
# D2
# F1
# D2
T4: <type 'frozenset'>
# T4
D2: <dict object at 0x7fa262b4f7f8>
F1: <function _remove at 0x7fa262bcd668>
D4: <dict object at 0x7fa26e566a28>
# D4
R1: <weakref at 0x7fa262bce578; to 'WeakSet' at 0x7fa262bcba10>
# R1
D2: <dict object at 0x7fa262b5a7f8>
# D2
# F1
# D2
F1: <function __call__ at 0x7fa262bcd7d0>
Co: <code object __call__ at 0x7fa26e4b2d30, file "/usr/lib/python2.7/site-packages/astropy/modeling/core.py", line 406>
# Co
D2: <dict object at 0x7fa262b597f8>
D4: <dict object at 0x7fa26e619168>
# D4
F1: <function __call__ at 0x7fa262bcd758>
Co: <code object __call__ at 0x7fa2652374b0, file "/usr/lib/python2.7/site-packages/astropy/modeling/core.py", line 400>
# Co
D4: <dict object at 0x7fa265230d70>
# D4
Ce: <cell at 0x7fa262bc3750: _CompoundModelMeta object at 0x55b9d8aa8cc0>
F2: <function _create_cell at 0x7fa26cc41938>
# F2
T2: <class '__main__.CompoundModel0'>
Name: CompoundModel0
Inputs: (u'x',)
Outputs: (u'y',)
Fittable parameters: (u'amplitude_0', u'mean_0', u'stddev_0', u'amplitude_1', u'mean_1', u'stddev_1')
Expression: [0] + [1]
Components: 
    [0]: <Gaussian1D(amplitude=1.0, mean=0.0, stddev=1.0)>

    [1]: <Gaussian1D(amplitude=1.0, mean=0.0, stddev=1.0)>
D2: <dict object at 0x7fa262b5b168>
F1: <function __call__ at 0x7fa262bcd7d0>
D2: <dict object at 0x7fa262b5b398>
# D2
# F1
D2: <dict object at 0x7fa262b5a168>
# D2
D2: <dict object at 0x7fa262b5a050>
# D2
# D2
# T2
# Ce
D2: <dict object at 0x7fa262bbdd70>
# D2
# F1
# D2
# F1
# D2
# T2
D2: <dict object at 0x7fa262b59d70>
D2: <dict object at 0x7fa262b59c58>
D2: <dict object at 0x7fa262b5a6e0>
# D2
D2: <dict object at 0x7fa262b5b6e0>
# D2
D2: <dict object at 0x7fa262b59e88>
# D2
# D2
D2: <dict object at 0x7fa262b5bb40>
Sl: slice(1, 2, None)
# Sl
# D2
D2: <dict object at 0x7fa262b5ba28>
Sl: slice(0, 1, None)
# Sl
# D2
D2: <dict object at 0x7fa262b5f050>
Sl: slice(5, 6, None)
# Sl
# D2
D2: <dict object at 0x7fa262b5bc58>
Sl: slice(2, 3, None)
# Sl
# D2
D2: <dict object at 0x7fa262b5bd70>
Sl: slice(3, 4, None)
# Sl
# D2
D2: <dict object at 0x7fa262b5be88>
Sl: slice(4, 5, None)
# Sl
# D2
# D2
```

**Comment by Lyalpha** [comment]
I get the equivalent until it raises the error after `# D2` on line 231, i.e. I am missing 
```
# F1
# D2
# T2
D2: <dict object at 0x7fa262b59d70>
D2: <dict object at 0x7fa262b59c58>
D2: <dict object at 0x7fa262b5a6e0>
# D2
D2: <dict object at 0x7fa262b5b6e0>
# D2
D2: <dict object at 0x7fa262b59e88>
# D2
# D2
D2: <dict object at 0x7fa262b5bb40>
Sl: slice(1, 2, None)
# Sl
# D2
D2: <dict object at 0x7fa262b5ba28>
Sl: slice(0, 1, None)
# Sl
# D2
D2: <dict object at 0x7fa262b5f050>
Sl: slice(5, 6, None)
# Sl
# D2
D2: <dict object at 0x7fa262b5bc58>
Sl: slice(2, 3, None)
# Sl
# D2
D2: <dict object at 0x7fa262b5bd70>
Sl: slice(3, 4, None)
# Sl
# D2
D2: <dict object at 0x7fa262b5be88>
Sl: slice(4, 5, None)
# Sl
# D2
# D2
```

I will try with the dev version, see if it also works for me.

**Comment by mmckerns** [comment]
I also wasn't able to replicate the error.  Possibly the difference is python `2.7.5` versus `2.7.11`?  I think @matsjoyce and I are on the latest python.

**Comment by Lyalpha** [comment]
Must be something updated in python between `2.7.5` and `2.7.11` as it appears to work on python `2.7.11` for myself also.

**Comment by Lyalpha** [comment]
One other peculiarity I've just noticed in my use case.

The code I posted above works fine in the interpretor now, or when run as a python script from the shell. However, when I try to import that script from within a python session, I again get a pickling error. (As before, using python's `pickle` seems to work.)

test.py:
```
from cStringIO import StringIO
#import cPickle as pickle     -> again, works with this line instead of dill
import dill as pickle
from astropy.modeling import models

s = StringIO()
g1 =  models.Gaussian1D()
pickle.dump(g1,s)
g2 =  models.Gaussian1D() + models.Gaussian1D()
pickle.dump(g2, s)
```
```
>>> import test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test.py", line 8, in <module>
    s2 = pickle.dumps(g2)
  File "lib/python2.7/site-packages/dill/dill.py", line 256, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "lib/python2.7/site-packages/dill/dill.py", line 249, in dump
    pik.dump(obj)
  File "lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "lib/python2.7/pickle.py", line 396, in save_reduce
    save(cls)
  File "/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "lib/python2.7/site-packages/dill/dill.py", line 1236, in save_type
    StockPickler.save_global(pickler, obj)
  File "lib/python2.7/pickle.py", line 754, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <class 'test.CompoundModel0'>
Name: CompoundModel0
Inputs: (u'x',)
Outputs: (u'y',)
Fittable parameters: (u'amplitude_0', u'mean_0', u'stddev_0', u'amplitude_1', u'mean_1', u'stddev_1')
Expression: [0] + [1]
Components:
    [0]: <Gaussian1D(amplitude=1.0, mean=0.0, stddev=1.0)>

    [1]: <Gaussian1D(amplitude=1.0, mean=0.0, stddev=1.0)>: it's not found as test.CompoundModel0
```

There is some discussion [here](https://github.com/astropy/astropy/pull/3867) about pickling of the compound models. I guess it is something with the dynamically generated nature of the CompoundModel class, but wondered if this scenario (i.e. importing modules and working interactively on these dynamic classes) can work with `dill`.

**Comment by mmckerns** [comment]
Yes, dynamically build classes can cause issues.  I would expect the same workaround implemented in the link you give above, could also do the trick for `dill`.  This may be a case that you'd want to use `dill.settings['byref'] = True` (which pickles by reference), or one of the other non-defaut `dill.settings`.
