### ISSUE TITLE
multiprocess.Connection objects not pickled properly

### ISSUE THREAD

**Issue by janssen** [uqfoundation/dill#177]
I'm seeing this error:

```
  File "C:\Users\wjanssen\AppData\Local\Temp\cbmx\lib\site-packages\dill\dill.py", line 260, in loads
    return load(file)
  File "C:\Users\wjanssen\AppData\Local\Temp\cbmx\lib\site-packages\dill\dill.py", line 250, in load
    obj = pik.load()
  File "C:\Users\wjanssen\AppData\Local\Temp\cbmx\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Users\wjanssen\AppData\Local\Temp\cbmx\lib\pickle.py", line 1089, in load_newobj
    obj = cls.__new__(cls, *args)
TypeError: Required argument 'handle' (pos 1) not found
```

which appears to be this bug:

https://bugs.python.org/issue4892

Is this fix not incorporated into dill?

Windows 10, Python 2.7.12, dill 0.2.5, multiprocess 0.70.4.

```
$ /tmp/cbmx/python -i
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import dill
>>> dill.__version__
'0.2.5'
>>> import multiprocess
>>> multiprocess.__version__
'0.70.4'
>>> quit()
$
```

The pickle itself is

```
'\x80\x02]q\x00cmultiprocess.queues\nQueue\nq\x01)\x81q\x02(\x8a\x04\xff\xff\xff\x7fc_multiprocess\nPipeConnection\nq\x03)\x81q\x04h\x03)\x81q\x05cmultiprocess.synchronize\nLock\nq\x06)\x81q\x07\x8a\x01\x08K\x01K\x01\x87q\x08bNcmultiprocess.synchronize\nBoundedSemaphore\nq\t)\x81q\n\x8a\x01\x0cK\x01J\xff\xff\xff\x7f\x87q\x0bbMd\x05tq\x0cba.'
```

**Comment by mmckerns** [comment]
So the answer is no.  I'm surprised that the patch was not applied to the `2.7` branch of `multiprocessing`, of which `multiprocess` is a fork.  It was applied to, and works in `3.x`.

Hmm… I'm not sure whether it is better to close this and open an issue for `multiprocess` (i.e apply the patch to the `2.x` branch), referencing this ticket... or to apply the patch directly within `dill`.

**Comment by mmckerns** [comment]
In python 3.5:
```
>>> import multiprocess
>>> c1,c2 = multiprocess.Pipe(duplex=False)
>>> c2.send(c1)
>>> c1.recv()
<multiprocess.connection.Connection object at 0x1062f8ef0>
>>> 
```
However, in python 2.7:
```
>>> import multiprocess
>>> c1,c2 = multiprocess.Pipe(duplex=False)
>>> c2.send(c1)
>>> c1.recv()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.6.dev0-py2.7.egg/dill/dill.py", line 273, in loads
    return load(file)
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.6.dev0-py2.7.egg/dill/dill.py", line 263, in load
    obj = pik.load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1089, in load_newobj
    obj = cls.__new__(cls, *args)
TypeError: Required argument 'handle' (pos 1) not found
```
and
```
>>> import multiprocess
>>> c1,c2 = multiprocess.Pipe(duplex=False)
>>> import dill
>>> dill.copy(c1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.6.dev0-py2.7.egg/dill/dill.py", line 206, in copy
    return loads(dumps(obj, *args, **kwds))
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.6.dev0-py2.7.egg/dill/dill.py", line 273, in loads
    return load(file)
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.6.dev0-py2.7.egg/dill/dill.py", line 263, in load
    obj = pik.load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1089, in load_newobj
    obj = cls.__new__(cls, *args)
TypeError: Required argument 'handle' (pos 1) not found
>>> 
```

**Comment by mmckerns** [comment]
This is no longer relevant as 2.x is no longer supported.
