### ISSUE TITLE
Cannot pickle instance of webdriver

### ISSUE THREAD

**Issue by marcos-alfredo** [uqfoundation/dill#178]
I am running the following code:

```
if __name__ == "__main__":
    import dill
    from pathos.helpers import freeze_support
    from selenium import webdriver
    freeze_support()
    driver = webdriver.Chrome()
    result = dill.dumps(driver)
    driver_2 = dill.loads(result)
    driver_2.get("http://www.google.com")
```

This is the result:

```
Traceback (most recent call last):
  File "webtest.py", line 7, in <module>
    result = dill.dumps(driver)
  File "C:\Python27\lib\site-packages\dill\dill.py", line 243, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "C:\Python27\lib\site-packages\dill\dill.py", line 236, in dump
    pik.dump(obj)
  File "C:\Python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\site-packages\dill\dill.py", line 835, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\site-packages\dill\dill.py", line 835, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\site-packages\dill\dill.py", line 835, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 313, in save
    (t.__name__, obj))
pickle.PicklingError: Can't pickle '_subprocess_handle' object: <_subprocess_han
dle object at 0x0229EAE0>
```

Searching through Stack Exchange I found out that dill has a detect functionality to help with pickling errors but I'm still not able to solve this.

This is what I tried:

```
if __name__ == "__main__":
    import dill
    from pathos.helpers import freeze_support
    from selenium import webdriver
    freeze_support()
    driver = webdriver.Chrome()
    dill.detect.errors(driver, depth=1)
```

The output is:

```
Traceback (most recent call last):
  File "webtest.py", line 17, in <module>
    dill.detect.errors(driver, depth=1)
  File "C:\Python27\lib\site-packages\dill\detect.py", line 292, in errors
    for attr in dir(obj) if not pickles(getattr(obj,attr),exact,safe)))
  File "C:\Python27\lib\site-packages\dill\detect.py", line 292, in <genexpr>
    for attr in dir(obj) if not pickles(getattr(obj,attr),exact,safe)))
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", l
ine 922, in orientation
    return self.execute(Command.GET_SCREEN_ORIENTATION)['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", l
ine 236, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py"
, line 163, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: unimplemented command: s
ession/755e4e6c0fc43c6e00510e15bf9edfca/orientation
```

My setup:

Windows 7 64
Python 2.7.11
Dill 0.2.5

**Comment by mmckerns** [comment]
I think this is the same issue: http://stackoverflow.com/questions/26805080/why-do-i-get-a-cant-pickle-when-i-try-to-run-a-function-and-kill-it-if-it

**Comment by mmckerns** [comment]
UI interface objects and other equally nasty objects tend not to pickle without significant effort.  `dill` doesn't support non-STL modules in general.  Maybe you will have to make it work.  Can you try a `dill.dumps` again, but with `dill.detect.trace(True)`?  Then post the results here.  If you can boil this down to a more minimal example, that would be good (the above can help).

I'm not sure why `dill.detect.errors` seems to be failing for you.

**Comment by matsjoyce** [comment]
I think the `getattr` is failing due to a property. Maybe `dill.detect.errors` should be extended to handle that?

**Comment by marcos-alfredo** [comment]
@mmckerns I checked that thread but their solution doesn't work for me. I'm trying to create the driver in the child process then send it back to the parent and use it there. Unfortunately doing everything in the child process would not work for me.

This is the output from adding `dill.detect.trace(True)` to the first script in the OP:

```
T4: <class 'selenium.webdriver.chrome.webdriver.WebDriver'>
# T4
D2: <dict object at 0x026E3F60>
T4: <class 'selenium.webdriver.chrome.service.Service'>
# T4
D2: <dict object at 0x02705150>
T4: <class 'subprocess.Popen'>
# T4
D2: <dict object at 0x02705540>
Fi: <open file '<fdopen>', mode 'rb' at 0x025C3180>
F2: <function _create_filehandle at 0x022700B0>
# F2
B2: <built-in function open>
# B2
# Fi
Traceback (most recent call last):
  File "C:\Git\Credentialing-Application-UI\ui_selenium_tests\webtest.py", line
8, in <module>
    result = dill.dumps(driver)
  File "C:\Python27\lib\site-packages\dill\dill.py", line 243, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "C:\Python27\lib\site-packages\dill\dill.py", line 236, in dump
    pik.dump(obj)
  File "C:\Python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\site-packages\dill\dill.py", line 835, in save_module_di
ct
    StockPickler.save_dict(pickler, obj)
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\site-packages\dill\dill.py", line 835, in save_module_di
ct
    StockPickler.save_dict(pickler, obj)
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\site-packages\dill\dill.py", line 835, in save_module_di
ct
    StockPickler.save_dict(pickler, obj)
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 313, in save
    (t.__name__, obj))
pickle.PicklingError: Can't pickle '_subprocess_handle' object: <_subprocess_han
dle object at 0x020FFAE0>
```

This is the code:

```
if __name__ == "__main__":
    import dill
    from pathos.helpers import freeze_support
    from selenium import webdriver
    freeze_support()
    dill.detect.trace(True)
    driver = webdriver.Firefox()
    result = dill.dumps(driver)
    driver_2 = dill.loads(result)
    driver.get("http://www.google.com")
```

**Comment by mmckerns** [comment]
@matsjoyce; done in 0e8e3d1c1ea903e4e8dafa12d00de8c14093f653

**Comment by mmckerns** [comment]
@marcos-alfredo: I can't seem to find where a `_subprocess_handle` object comes from.  Do you happen to know?  Also, is it possible to try one of the variants in `dill.settings`?

**Comment by mmckerns** [comment]
@marcos-alfredo: Following up, is this still an issue, or can it be closed?

**Comment by mmckerns** [comment]
I'm closing this, as `selenium.webdriver` objects are too specialized an object for `dill` to add a special case for.  Two paths forward (are apparent to me): either submit an issue to selenium about serialization of their `webdriver` objects, or serialize only the data from driver state and not the object itself.  Feel free to reopen this issue if needed.
