### ISSUE TITLE
Dill tries to import irrelevant modules when deserialising a serialised function

### ISSUE THREAD

**Issue by cynix** [uqfoundation/dill#188]
I'm trying to serialise a function and send it across to another process, like this:

client.py:

```
from my_module import Connection

class Client(Connection):
    def foo(self):
        some_var = 42
        def some_function(param):
            print some_var, param

        self.send(dill.dumps(some_function))
```

server.py:

```
class Server(object):
    def recv(self, data):
        func = dill.loads(data)
        func(123)
```

As you can see, `some_function()` is a free-standing function that does not have any dependency on `my_module`. However, when the server tries to deserialise the received data, dill complains that it can't import my_module. Is there any way to make dill not serialise irrelevant imports when serialising a function?

**Comment by mmckerns** [comment]
You should provide a minimal working example.  Yours is not a complete example.

However, I do have a minimal example... this time.
```
# FILE: client.py 
import dill
from my_module import Connection

class Client(Connection):
    def foo(self):
        some_var = 42
        def some_function(param):
            print some_var, param

        return self.send(dill.dumps(some_function))
```
```
# FILE: my_module.py 
class Connection(object):
  def send(self, args):
    return args
```
```
# FILE: server.py 
import dill

class Server(object):
    def recv(self, data):
        func = dill.loads(data)
        func(123) 
```
START INTERPRETER...
```
>>> import client
>>> c = client.Client()
>>> x = c.foo()
>>> x
'\x80\x02cdill.dill\n_create_function\nq\x00(cdill.dill\n_load_type\nq\x01U\x08CodeTypeq\x02\x85q\x03Rq\x04(K\x01K\x01K\x01K\x13U\r\x88\x00\x00G|\x00\x00GHd\x00\x00Sq\x05N\x85q\x06)U\x05paramq\x07\x85q\x08U\tclient.pyq\tU\rsome_functionq\nK\x07U\x02\x00\x01q\x0bU\x08some_varq\x0c\x85q\r)tq\x0eRq\x0fcclient\n__dict__\nh\nNcdill.dill\n_create_cell\nq\x10K*\x85q\x11Rq\x12\x85q\x13}q\x14tq\x15Rq\x16.'
>>> 
```
RESTART INTERPRETER
```
>>> import server
>>> s = server.Server()
>>> x = '\x80\x02cdill.dill\n_create_function\nq\x00(cdill.dill\n_load_type\nq\x01U\x08CodeTypeq\x02\x85q\x03Rq\x04(K\x01K\x01K\x01K\x13U\r\x88\x00\x00G|\x00\x00GHd\x00\x00Sq\x05N\x85q\x06)U\x05paramq\x07\x85q\x08U\tclient.pyq\tU\rsome_functionq\nK\x07U\x02\x00\x01q\x0bU\x08some_varq\x0c\x85q\r)tq\x0eRq\x0fcclient\n__dict__\nh\nNcdill.dill\n_create_cell\nq\x10K*\x85q\x11Rq\x12\x85q\x13}q\x14tq\x15Rq\x16.'
>>> s.recv(x)
42 123
```
It works.  Now simulate using a different machine...
```
$ rm *pyc
$ mv client.py _client.py
$ mv my_module.py _my_module.py 
```
RESTART INTERPRETER
```
>>> import server
>>> s = server.Server()
>>> x = '\x80\x02cdill.dill\n_create_function\nq\x00(cdill.dill\n_load_type\nq\x01U\x08CodeTypeq\x02\x85q\x03Rq\x04(K\x01K\x01K\x01K\x13U\r\x88\x00\x00G|\x00\x00GHd\x00\x00Sq\x05N\x85q\x06)U\x05paramq\x07\x85q\x08U\tclient.pyq\tU\rsome_functionq\nK\x07U\x02\x00\x01q\x0bU\x08some_varq\x0c\x85q\r)tq\x0eRq\x0fcclient\n__dict__\nh\nNcdill.dill\n_create_cell\nq\x10K*\x85q\x11Rq\x12\x85q\x13}q\x14tq\x15Rq\x16.'
>>> s.recv(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "server.py", line 5, in recv
    func = dill.loads(data)
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.6.dev0-py2.7.egg/dill/dill.py", line 277, in loads
    return load(file)
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.6.dev0-py2.7.egg/dill/dill.py", line 266, in load
    obj = pik.load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.6.dev0-py2.7.egg/dill/dill.py", line 423, in find_class
    return StockUnpickler.find_class(self, module, name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1130, in find_class
    __import__(module)
ImportError: No module named client
>>> 
```

**Comment by mmckerns** [comment]
Essentially the issue is that the modules you are trying to ship are not on the server machine, or if they are, they are not  on the `PYTHONPATH`.  If they are installed modules (or at least on the `PYTHONPATH`), the code above should work.

Now, the question is: can `dill` not ship these modules?  The answer is it depends.

**Comment by mmckerns** [comment]
If you add `dill.settings['recurse'] = True` to `client.py`, then it should work.
```
>>> import client
>>> c = client.Client()
>>> x = c.foo()
>>> x
'\x80\x02cdill.dill\n_create_function\nq\x00(cdill.dill\n_load_type\nq\x01U\x08CodeTypeq\x02\x85q\x03Rq\x04(K\x01K\x01K\x01K\x13U\r\x88\x00\x00G|\x00\x00GHd\x00\x00Sq\x05N\x85q\x06)U\x05paramq\x07\x85q\x08U\tclient.pyq\tU\rsome_functionq\nK\x08U\x02\x00\x01q\x0bU\x08some_varq\x0c\x85q\r)tq\x0eRq\x0f}q\x10h\nNcdill.dill\n_create_cell\nq\x11K*\x85q\x12Rq\x13\x85q\x14}q\x15tq\x16Rq\x17.'
```
REMOVE/MOVE FILES
```
$ mv client.py _client.py
$ mv my_module.py _my_module.py
$ rm *pyc
```
RESTART INTERPRETER
```
>>> import server
>>> s = server.Server()
>>> x = '\x80\x02cdill.dill\n_create_function\nq\x00(cdill.dill\n_load_type\nq\x01U\x08CodeTypeq\x02\x85q\x03Rq\x04(K\x01K\x01K\x01K\x13U\r\x88\x00\x00G|\x00\x00GHd\x00\x00Sq\x05N\x85q\x06)U\x05paramq\x07\x85q\x08U\tclient.pyq\tU\rsome_functionq\nK\x08U\x02\x00\x01q\x0bU\x08some_varq\x0c\x85q\r)tq\x0eRq\x0f}q\x10h\nNcdill.dill\n_create_cell\nq\x11K*\x85q\x12Rq\x13\x85q\x14}q\x15tq\x16Rq\x17.'
>>> s.recv(x)
42 123
```

**Comment by cynix** [comment]
Thanks for the reply. I did eventually figure out that I needed the 'recurse' flag. However, as you pointed out, the question remains whether `dill` can simply not ship irrelevant modules and still have it work on the remote end.

**Comment by mmckerns** [comment]
@cynix: That is exactly what `dill.settings['recurse'] = True` does.

**Comment by cynix** [comment]
Apologies, I must've misunderstood what it did. I thought it meant it will recursively ship all modules to satisfy requirements on the remote side.

**Comment by mmckerns** [comment]
@cynix: Nope, `dill` won't do that.  If you want something that will ship and install modules to remote resources, I built `pox` to handle that.  However, it's by far better and easier to just have all modules you will need already installed on remote resources.  Installation of modules on remote resources can be tricky to say the least.
