### ISSUE TITLE
can't pickle select.poll object

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/dill#207]
```
>>> import select
>>> import dill
>>> dill.copy(select.poll())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.6.dev0-py2.7.egg/dill/dill.py", line 209, in copy
    return loads(dumps(obj, *args, **kwds))
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.6.dev0-py2.7.egg/dill/dill.py", line 259, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/Users/mmckerns/lib/python2.7/site-packages/dill-0.2.6.dev0-py2.7.egg/dill/dill.py", line 252, in dump
    pik.dump(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 313, in save
    (t.__name__, obj))
pickle.PicklingError: Can't pickle 'poll' object: <select.poll object at 0x107acfc00>
>>> 
```
This error came about from [pathos #85](https://github.com/uqfoundation/pathos/issues/85), reported by @maxbitcoin.

**Comment by Alonreznik** [comment]
Hi There.
Any updates on that issue? 

Thanks

**Comment by MeTaNoV** [comment]
Hi, I am facing a similar issue working on an IO connector for the Apache Beam project: https://issues.apache.org/jira/browse/BEAM-5148
More on the issue here: https://stackoverflow.com/questions/52040923/error-trying-to-implement-a-mongodb-io-connector-sink

**Comment by mmckerns** [comment]
@Alonreznik @MeTaNoV: Sorry no updates on this yet.

**Comment by mmckerns** [comment]
In theory, it looks like one should be able to extract the registered `socket` objects (or file descriptors) from the `poll` object, and then pickle them... then to reconstitute, build a new `poll` object and register the `socket` objects.  It doesn't seem that `select.poll` produces something that is a python class instance (i.e. `select` is built in C, so the `poll` object is purely a C built-in)... so my best guess here is to extract and pickle it's state... then build a new one, and push in the reconstituted state objects.

**Comment by MeTaNoV** [comment]
Thanks @mmckerns for the hint. Apart from the fact that your solution might not be easily implemented by someone else than you or any other contributor of Dill, my specific use-case might not even fit.
Let me give you more detail why I think it might be like that (and I would be happy to be proved wrong).
Apache Beam being a distributed pipeline execution framework, Dill is used to pickle the code to be executed on different instances. Therefore, I don't think that saving a socket object or FD is something than can be re-used on different instances... 
Now that I looked at the original issue coming from Pathos, I can see that the usage of `pymongo` is the same origin of the problem... 
So, I suppose that we are stuck at this point... The only way that I see ATM would be to have a REST client API or something other than `pymongo` that can be pickled to access the DB...

**Comment by mmckerns** [comment]
@MeTaNoV: I agree about the difficulty of the work-around.  The point was moreover that it should be possible, with some work, to make the `poll` object serializable.  When that will be done is not known, and I've not assigned it to a milestone yet.

If you do want references to how `dill` handles file descriptors, you can explore that from https://github.com/uqfoundation/dill/issues/57.

**Comment by GiliR4t1qbit** [comment]
Any updates? I'm seeing this issue as well, and need a fix or a workaround....

**Comment by GiliR4t1qbit** [comment]
@mmckerns: switching from ProcessPool to ThreadPool seems to get rid of the problem. It's not clear to me what this change actually means, and I see that in pathos' multiprocessing.py the ThreadPool import is commented as being for "backward compatibility", which makes me think this isn't a good solution (https://github.com/uqfoundation/pathos/blob/master/pathos/multiprocessing.py). Can you shed any light on this?

**Comment by mmckerns** [comment]
@GiliR4t1qbit: There are several pools available from pathos.  `ProcessPool` which uses `multiprocess` (i.e. multiple python instances, and multiple processes) and requires full object serialization; `ThreadPool` which uses `threading` (i.e. one python instance with multiple threads) and requires much lighter object serialization.  There is also `ParallelPool` which uses `subprocess` directly, with source code extraction as opposed to serialization.  So, I'd expect other of the pools might work, with `ThreadPool` being the most likely.. and it also further confirms that the issue is serialization of the `poll` object.

**Comment by GiliR4t1qbit** [comment]
@mmckerns: Thanks - I tried switching to ThreadPool but discovered that my program seems to only be using one core at all times... This also seems to be the case when using multiprocessing.dummy (which is a wrapper for the threading module). Reading about it, it seems for the CPU bound (and not I/O bound) I actually want to use multiprocessing (multithreading held back to one core by the GIL), but with multiprocessing I seem to run into issues with serialization (when using both multiprocessing and pathos), as seen above. So switching to ThreadPool doesn't seem to be a good solution for my case. Is there another way to avoid the "can't pickle select.poll object" issue?

**Comment by GiliR4t1qbit** [comment]
I found a solution, such that I can now use ProcessPool. This involved splitting off the worker code from a larger class that was not serializable (due to having the poll object in a constituent of it).

**Comment by James-E-A** [comment]
Considering that neither `io.FileIO` nor `socket.socket` are, themselves, picklable... how would this even be possible in theory? Do you mean to first implement pickling for those classes? Will there be any way to ensure that the recipient is resolving a given file-descriptor number to the *same* OS-level object that the sender meant it to refer to?

**Comment by mmckerns** [comment]
@James-E-A: files can be serialized with `dill`, where the file handling is described here: https://github.com/uqfoundation/dill/blob/a27d21c12a1fe63e55f429c7d8639fe62ba2b51c/dill/_dill.py#L229
Sockets currently aren't serializable with `dill`.  Not all of an object's components need to be serializable, just the state of an object... so there are serializable objects that are built from non-serializable objects (i.e. when those objects contain critical state that can be saved otherwise).
