### ISSUE TITLE
Error with datetime.strftime

### ISSUE THREAD

**Issue by ZuoMatthew** [uqfoundation/dill#219]
Hi,

Dill is a great tool which helps us a lot in our daily job.
Today we found a strange problem when working with datetime functions, our simple test code as attached.
when code runs to line 5, a KeyError: '__builtins__' comes up. Maybe it is a bug?

codes:

from datetime import datetime

def test():
    utcNow1 = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')

import dill

dill.settings['recurse'] = True

a = dill.dumps(test)

al = dill.loads(a)
al()

**Comment by ZuoMatthew** [comment]
Sorry, I had trouble to upload my code and have to paste it.

**Comment by matsjoyce** [comment]
Formatted test case:
```py3
import dill, sys
dill.dill._trace(1)
from datetime import datetime

def test():
    print(globals())
    utcNow1 = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')

import dill

dill.settings['recurse'] = True
print(test.__globals__)
a = dill.dumps(test)
al = dill.loads(a)
test()
al()
```
Output:
```
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7ff2b8f8d6d8>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': 'a.py', '__cached__': None, 'dill': <module 'dill' from '/home/matthew/GitHub/dill/dill/__init__.py'>, 'sys': <module 'sys' (built-in)>, 'datetime': <class 'datetime.datetime'>, 'test': <function test at 0x7ff2b903ce18>}
F1: <function test at 0x7ff2b903ce18>
F2: <function _create_function at 0x7ff2b82ef268>
# F2
Co: <code object test at 0x7ff2b900e8a0, file "a.py", line 5>
T1: <class 'code'>
F2: <function _load_type at 0x7ff2b82ef158>
# F2
# T1
# Co
D2: <dict object at 0x7ff2b825ab40>
T4: <class 'datetime.datetime'>
# T4
B1: <built-in function globals>
F2: <function _get_attr at 0x7ff2b82efbf8>
# F2
# B1
B1: <built-in function print>
# B1
# D2
D2: <dict object at 0x7ff2b9013558>
# D2
# F1
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7ff2b8f8d6d8>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': 'a.py', '__cached__': None, 'dill': <module 'dill' from '/home/matthew/GitHub/dill/dill/__init__.py'>, 'sys': <module 'sys' (built-in)>, 'datetime': <class 'datetime.datetime'>, 'test': <function test at 0x7ff2b903ce18>, 'a': b'\x80\x03cdill.dill\n_create_function\nq\x00(cdill.dill\n_load_type\nq\x01X\x08\x00\x00\x00CodeTypeq\x02\x85q\x03Rq\x04(K\x00K\x00K\x01K\x02KCC\x1ct\x00t\x01\x83\x00\x83\x01\x01\x00t\x02j\x03\x83\x00j\x04d\x01\x83\x01}\x00d\x00S\x00q\x05NX\x11\x00\x00\x00%Y-%m-%d %H:%M:%Sq\x06\x86q\x07(X\x05\x00\x00\x00printq\x08X\x07\x00\x00\x00globalsq\tX\x08\x00\x00\x00datetimeq\nX\x06\x00\x00\x00utcnowq\x0bX\x08\x00\x00\x00strftimeq\x0ctq\rX\x07\x00\x00\x00utcNow1q\x0e\x85q\x0fX\x04\x00\x00\x00a.pyq\x10X\x04\x00\x00\x00testq\x11K\x05C\x04\x00\x01\n\x01q\x12))tq\x13Rq\x14}q\x15(X\x08\x00\x00\x00datetimeq\x16cdatetime\ndatetime\nq\x17X\x07\x00\x00\x00globalsq\x18cdill.dill\n_get_attr\nq\x19X\x08\x00\x00\x00builtinsq\x1aX\x07\x00\x00\x00globalsq\x1b\x86q\x1cRq\x1dX\x05\x00\x00\x00printq\x1eh\x19h\x1aX\x05\x00\x00\x00printq\x1f\x86q Rq!uh\x11NN}q"tq#Rq$.', 'al': <function test at 0x7ff2b7ffc598>}
{'datetime': <class 'datetime.datetime'>, 'globals': <built-in function globals>, 'print': <built-in function print>}
Traceback (most recent call last):
  File "a.py", line 16, in <module>
    al()
  File "a.py", line 7, in test
    utcNow1 = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')
KeyError: '__builtins__'
```

It seems to be a bug in `dill.detect.globalvars` removing the reference to `__builtins__`.

**Comment by ZuoMatthew** [comment]
@matsjoyce thank you, is there any way to fix or work around this bug? I have to pickle functions with such datetime.strftime.

**Comment by mmckerns** [comment]
light edit of the test case:

 ```
import dill
 dill.dill._trace(1)
 from datetime import datetime
 
 def test():
     utcNow1 = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')
 
 dill.settings['recurse'] = True
 a = dill.loads(dill.dumps(test))
 print(test.__globals__)
 print(a.__globals__)
 test()
 a()
```

Note it "works" in python27, in that it doesn't throw an error.  However, what you get is that `a.__globals__` doesn't point to `globals()`, while `test.__globals__` does.  Same result in python3.x, except there's also an error thrown.

I'll first try fix the `KeyError` in python3.x.

Worse still... if you move the import of `datetime` inside of `test`, you get a different error.

```
{'test': <function test at 0x10972d0d0>, '__builtins__': <module 'builtins' (built-in)>, '__spec__': None, '__cached__': None, '__doc__': None, '__file__': 'test_builtins.py', 'dill': <module 'dill' from '/Users/mmckerns/lib/python3.5/site-packages/dill-0.2.7.dev0-py3.5.egg/dill/__init__.py'>, '__name__': '__main__', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x10977d128>, 'a': <function test at 0x109bbd6a8>, '__package__': None}
{}
Traceback (most recent call last):
  File "test_builtins.py", line 13, in <module>
    a()
  File "test_builtins.py", line 5, in test
    from datetime import datetime
ImportError: __import__ not found
```

In sort, it seems it all stems from `__globals__` not being hooked up correctly.

**Comment by RAbraham** [comment]
I'm getting the `ImportError: __import__ not found` error too. Do you think this is a fundamental issue in `__globals__` that cannot be fixed or is there a workaround or perhaps a fix in the roadmap?

**Comment by RAbraham** [comment]
So I get the above error when I run the command line tool I made BUT I do not get the error if I directly call the python function that is invoked by the command line tool. Sorry, I need to investigate this more.

**Comment by ravwojdyla** [comment]
hi @mmckerns , thanks for all the work. Is there any update on this? I am getting this error in `0.2.9` and `0.3.0` for python 3.6.8. If there is no progress, do you have any pointers that I could start with to fix this issue?

As a workaround in my code, I monkeypatched the `_create_function` to add `__builtins__` if they not present in the function's `__globals__`, something like this:

```
def _fixed_create_function(
    fcode, fglobals, fname=None, fdefaults=None, fclosure=None, fdict=None
):
    # same as FunctionType, but enable passing __dict__ to new function,
    # __dict__ is the storehouse for attributes added after function creation
    if fdict is None:
        fdict = dict()
    func = FunctionType(fcode, fglobals or dict(), fname, fdefaults, fclosure)
    func.__dict__.update(fdict)  # XXX: better copy? option to copy?

    # THE WORKAROUND:
    # if the function was serialized without recurse, fglobals would actually contain
    # __builtins__, but because of recurse only the referenced modules/objects
    # end up in fglobals and we are missing the important __builtins__
    if "__builtins__" not in func.__globals__:
        func.__globals__["__builtins__"] = globals()["__builtins__"]
    return func

import dill
dill._dill._create_function = _alpine_create_function
```

This fixes the problem of both "local" import in recursively serialized function and also the problem of using datetime module which seems to depend on `__builtins__` in some way:

```
def get_fun_with_strftime() -> typ.Callable[[], str]:
    def fun_with_strftime() -> str:
        return datetime.datetime.strptime("04-01-1643", "%d-%m-%Y").strftime(
            "%Y-%m-%d %H:%M:%S"
        )

    return fun_with_strftime


def test_doc_dill_issue_219() -> None:
    # this test would fail with KeyError: '__builtins__'
    import dill
    back_fn = dill.loads(
        dill.dumps(get_fun_with_strftime(), recurse=True)
    )
    assert back_fn() == "1643-01-04 00:00:00"
```

```
def get_fun_with_internal_import() -> typ.Callable[[], typ.Pattern]:
    # this is a bug in dill, but we have an internal fix via dill_fix_plugin, so this documents that it works
    def fun_with_import() -> typ.Pattern:
        import re

        return re.compile("$")

    return fun_with_import


def test_method_with_internal_import_should_work() -> None:
    # this test would fail with ImportError: __import__ not found
    import re
    import dill

    back_fn = dill.loads(
        dill.dumps(get_fun_with_internal_import(), recurse=True)
    )
    # globals are not properly wired, __import__ is a __builtin__
    vars = inspect.getclosurevars(back_fn)
    assert vars.globals == {}
    assert vars.nonlocals == {}
    assert back_fn() == re.compile("$")
    assert "__builtins__" in back_fn.__globals__
```

I assume that this is probably not a proper fix, but I would love to hear some pointers as to how to fix this upstream in dill.

**Comment by ravwojdyla** [comment]
Hi @mmckerns - hope, you're well. Update update on this ^

**Comment by adriangonz** [comment]
We just hit this issue recently when trying to move from `dill` to `cloudpickle`. 

Are there any caveats on using the patched version from @ravwojdyla? Is there any reason not to update the `_create_function` in `dill`'s codebase with this fix?

https://github.com/uqfoundation/dill/blob/846b888ef957dc1991464b562df425aa35142cb8/dill/_dill.py#L594-L603

**Comment by mmckerns** [comment]
Apparently this slid off my radar somehow.  I need to look into the impact of the proposed patch.

**Comment by mmckerns** [comment]
Can't see any bad side effects... thus I've made a patch.  Thanks.
