### ISSUE TITLE
dill incorrectly attempts to serialize generators when using Python 3.3; unable to deserialize picked objects

### ISSUE THREAD

**Issue by rs2** [uqfoundation/dill#227]
* **Python 3.3**
```python
conda create -n pydill33 python=3.3 dill -y
source activate pydill33 & python -c "import dill; g = (x for x in range(3)); print(g.__reduce_ex__(3)); next(g); pickled = dill.dumps(g); dill.loads(pickled)" & deactivate
```
produces
```
(<function __newobj__ at 0x0000000002B4B730>, (<class 'generator'>,), None, None, None)
Traceback (most recent call last):
...
    dispatch[key[0]](self)
  File "C:\Anaconda3\envs\pydill33\lib\pickle.py", line 1094, in load_newobj
    obj = cls.__new__(cls, *args)
TypeError: object.__new__(generator) is not safe, use generator.__new__()
```
* **Python 3.4+**
```python
conda create -n pydill34 python=3.4 dill -y
source activate pydill34 & python -c "import dill; g = (x for x in range(3)); print(g.__reduce_ex__(3)); next(g); pickled = dill.dumps(g); dill.loads(pickled)" & deactivate
```
results in the expected `__reduce_ex__` exception, which also prevents the generator from being pickled.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: can't pickle generator objects
```

**Comment by mmckerns** [comment]
I'm not sure what your point here is.  Is it that for 3.3, `dill` fails on `load` while `pickle` fails on `dump` for generators?  That's what it sounds like your issues is to me.

I could see how that's a bad thing, so as of fbea4599c223ff50b08c6b5e31ed7c28e54ddbc8, `dill` throws a `PicklingError` on `dump` to mirror the behavior of `pickle` for python 3.1-3.3.  Please reopen this ticket if I misunderstood, and didn't handle your issue.
