### ISSUE TITLE
Can't pickle on Windows

### ISSUE THREAD

**Issue by Flood1993** [uqfoundation/dill#233]
Hello,

The following is a minimal reproducible example of a problem I'm having on Windows:

```python
from multiprocessing import Process
import dill

def function():
    class B():
        pass

    dill.dumps(B)

if __name__ == '__main__':
    p = Process(target=function)
    p.start()
    p.join()
```

I tried running that code in Ubuntu 17.04 and in Windows 10, both using Python 3.6.1. In Ubuntu it runs OK, but under Windows it crashes with the following output:

```
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Gan-N\Miniconda3\envs\osbrain\lib\pickle.py", line 918, in save_global
    obj2, parent = _getattribute(module, name)
  File "C:\Users\Gan-N\Miniconda3\envs\osbrain\lib\pickle.py", line 266, in _getattribute
    .format(name, obj))
AttributeError: Can't get local attribute 'function.<locals>.B' on <function function at 0x0000028D22201D90>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gan-N\Miniconda3\envs\osbrain\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Users\Gan-N\Miniconda3\envs\osbrain\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Gan-N\Code\osbrain\dill_test.py", line 8, in function
    dill.dumps(B)
  File "C:\Users\Gan-N\Miniconda3\envs\osbrain\lib\site-packages\dill\dill.py", line 259, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "C:\Users\Gan-N\Miniconda3\envs\osbrain\lib\site-packages\dill\dill.py", line 252, in dump
    pik.dump(obj)
  File "C:\Users\Gan-N\Miniconda3\envs\osbrain\lib\pickle.py", line 409, in dump
    self.save(obj)
  File "C:\Users\Gan-N\Miniconda3\envs\osbrain\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\Gan-N\Miniconda3\envs\osbrain\lib\site-packages\dill\dill.py", line 1258, in save_type
    StockPickler.save_global(pickler, obj)
  File "C:\Users\Gan-N\Miniconda3\envs\osbrain\lib\pickle.py", line 922, in save_global
    (obj, module_name, name))
_pickle.PicklingError: Can't pickle <class '__mp_main__.function.<locals>.B'>: it's not found as __mp_main__.function.<locals>.B
```

I can get it working by simply moving the class to the top level of the module, and that would be good enough for me. However, I was wondering if this is a bug related to `dill` or I'm missing something important.

**Comment by matsjoyce** [comment]
Could you try adding `p.join()`? I'm running python 3.6.1 on Arch Linux, and it errors out, as expected (see #85).

**Comment by Flood1993** [comment]
I added the `p.join()` call. Also, followed the chain of linked issues and managed to get it working on both systems with a work around you proposed on #56 .

Working with the following modification:
```python

def function():
    class B():
        pass
    B.__module__ = '__main__'
    dill.dumps(B)

```

I will need to see if it has any side effects on my real life case, and also take a look at the other proposals. 

Thank you @matsjoyce !

**Comment by mmckerns** [comment]
@Flood1993: thanks for reporting.
