### ISSUE TITLE
SystemError: unknown opcode

### ISSUE THREAD

**Issue by tfolkman** [uqfoundation/dill#235]
Hi,

I used dill to package up an object in OSX and it works great! I can then load the object with dill in OSX and all is well.

When I try to take this same object and use it with Linux, though, I a SystemError: unknown opcode. The dill load command works fine, but when actually calling a function from this loaded object I get the error. Any idea what might be happening? Thanks!

XXX lineno: 59, opcode: 0
[2017-07-14 00:00:32,589] ERROR in app: Exception on /process_data/ [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/src/app.py", line 61, in process_features
    exp = explainer.explain_instance(X, xgb_prediction, num_features=10, top_labels=1)
  File "/opt/conda/lib/python3.6/site-packages/lime/lime_tabular.py", line 249, in explain_instance
    data, inverse = self.__data_inverse(data_row, num_samples)
  File "/opt/conda/lib/python3.6/site-packages/lime/lime_tabular.py", line 400, in __data_inverse
    first_row = self.discretizer.discretize(data_row)
  File "/opt/conda/lib/python3.6/site-packages/lime/discretize.py", line 92, in discretize
    ret[feature] = int(self.lambdas[feature](ret[feature]))
  File "/Users/tfolkman/anaconda3/lib/python3.5/site-packages/lime/discretize.py", line 59, in <lambda>
    discretized = self.lambdas[feature](data[:, feature])
SystemError: unknown opcode

**Comment by mmckerns** [comment]
Can you boil your code down to a minimal example, so that I can try it?  That will be the easiest way I can help.  Also, it would help to have info on your version of linux and of dill.  I see you are using python 3.5.

**Comment by tfolkman** [comment]
Hey - thanks for the quick response. I was able to get around the dill dependency, but if I find some time, I will upload a simple example. It seemed like dill wasn't work cross platform for me.

**Comment by mmckerns** [comment]
Ok.
