### ISSUE TITLE
dill.check fails with FileNotFoundError for relatively large data

### ISSUE THREAD

**Issue by albertogomcas** [uqfoundation/dill#242]
Using dill version 0.2.7.1 in windows, all of the following:

`dill.check(list(range(4484))) # minimum number that fails in my tests`
`dill.check(np.arange(4899, dtype=np.int16)) # minimum number that fails in my tests`

fail with  FileNotFoundError: [WinError 206] The filename or extension is too long

```
dill.check(list(range(4484)))
Traceback (most recent call last):

  File "<ipython-input-67-6a4bcdd1e08d>", line 1, in <module>
    dill.check(list(range(4484)))

  File "C:\Users\alberto.gomez-casado\AppData\Local\Continuum\Anaconda3\envs\toscapy1\lib\site-packages\dill\dill.py", line 1425, in check
    msg = "SUCCESS" if not subprocess.call(msg.split(None,2)) else "LOAD FAILED"

  File "C:\Users\alberto.gomez-casado\AppData\Local\Continuum\Anaconda3\envs\toscapy1\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:

  File "C:\Users\alberto.gomez-casado\AppData\Local\Continuum\Anaconda3\envs\toscapy1\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)

  File "C:\Users\alberto.gomez-casado\AppData\Local\Continuum\Anaconda3\envs\toscapy1\lib\subprocess.py", line 990, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 206] The filename or extension is too long
```

However dumps / dump and load work fine with the same (and much larger) amount of data.

**Comment by mmckerns** [comment]
I see the same behavior on a MacOS with python 3.6.3 and the latest `dill` when I increase `4484` to `100000` or so.

**Comment by stablum** [comment]
On Linux:
```
>>> dill.check(list(range(0,1000000)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/francesco/.local/lib/python3.6/site-packages/dill/dill.py", line 1425, in check
    msg = "SUCCESS" if not subprocess.call(msg.split(None,2)) else "LOAD FAILED"
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 7] Argument list too long
>>> dill.__version__
'0.2.7.1'
```
