### ISSUE TITLE
Cannot pickle lambdas from SymPy with modules='numpy'

### ISSUE THREAD

**Issue by mvanvleet** [uqfoundation/dill#247]
Possibly related issue to Issue #104 : while dill now can pickle most sympy functions, I run into pickling errors depending on my choice of the modules optional argument. Here's a minimal working example modified from #104:

```python
import sympy
import dill

dill.settings['recurse'] = True

# put multiple symbols in scope
x, y, z = sympy.symbols('x y z')

# create expression, simple for example
expr = sympy.sqrt(2*x) + y

# generate anonymous function
#func = sympy.lambdify((x, y), expr,modules='numpy')   # This fails
func = sympy.lambdify((x, y), expr,modules='numexpr')  # This works

# pickle and unpickle lambda expression
pickled_func = dill.dumps(func)
new_func = dill.loads(pickled_func)
print new_func(2,2)

```

Using `modules='numexpr'` works fine, however using `modules='numpy'` results in the following error:

```python

Traceback (most recent call last):
  File "test.py", line 17, in <module>
    pickled_func = dill.dumps(func)
  File "/home/mvanvleet/anaconda2/lib/python2.7/site-packages/dill/dill.py", line 281, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/home/mvanvleet/anaconda2/lib/python2.7/site-packages/dill/dill.py", line 274, in dump
    pik.dump(obj)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mvanvleet/anaconda2/lib/python2.7/site-packages/dill/dill.py", line 1363, in save_function
    obj.__dict__), obj=obj)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 401, in save_reduce
    save(args)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mvanvleet/anaconda2/lib/python2.7/site-packages/dill/dill.py", line 1098, in save_cell
    pickler.save_reduce(_create_cell, (f,), obj=obj)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 401, in save_reduce
    save(args)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mvanvleet/anaconda2/lib/python2.7/site-packages/dill/dill.py", line 871, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 422, in save_reduce
    self._batch_setitems(dictitems)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 686, in _batch_setitems
    save(k)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/mvanvleet/anaconda2/lib/python2.7/site-packages/dill/dill.py", line 1299, in save_type
    StockPickler.save_global(pickler, obj)
  File "/home/mvanvleet/anaconda2/lib/python2.7/pickle.py", line 759, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <type 'numpy.uint64'>: it's not the same object as numpy.uint64

```

Any ideas what might be causing this error, and if it's fixable? In case it's important, I'm using Anaconda2-5.0.1-Linux-x86_64 with the following package versions:

```python
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct 16 2017, 17:29:19)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.__version__
'1.1.2.dev'
>>> import dill
>>> dill.__version__
'0.2.7.1'
```

**Comment by yycho0108** [comment]
Also having this issue. Can someone look into this?

**Comment by mmckerns** [comment]
Looks like this works now.  Closing
