### ISSUE TITLE
Error serializing itertools.repeat with Python 2.7.

### ISSUE THREAD

**Issue by ddebrunner** [uqfoundation/dill#251]
This works on Python 3.5 and `rd` is iterable.
Using dill 0.2.7.1
```
import itertools
import dill

r = itertools.repeat(9)
dr = dill.dumps(r)
rd = dill.loads(dr)
```

On Python 2.7 this occurs:
```
Traceback (most recent call last):
  File "dill_repeat.py", line 6, in <module>
    rd = dill.loads(dr)
  File "/home/streamsadmin/anaconda2/lib/python2.7/site-packages/dill/dill.py", line 299, in loads
    return load(file)
  File "/home/streamsadmin/anaconda2/lib/python2.7/site-packages/dill/dill.py", line 288, in load
    obj = pik.load()
  File "/home/streamsadmin/anaconda2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/streamsadmin/anaconda2/lib/python2.7/pickle.py", line 1089, in load_newobj
    obj = cls.__new__(cls, *args)
TypeError: Required argument 'object' (pos 1) not found
```

**Comment by matsjoyce** [comment]
As far an I remember, serializing iterators is a python 3 feature, so dill has nothing to do with the success or failure in either case. Just use python 3? 😄

**Comment by ddebrunner** [comment]
Thanks @matsjoyce I didn't know that, seems like it was new in protocol 4 (PEP3154).

It was an existing Python 3 test case that I started running on 2.7.

**Comment by mmckerns** [comment]
Yes, I can confirm that serializing iterators are a feature in python 3 only.  There's a critical bit of C code that is missing in python 2 in the python-C api that would be needed to serialize iterators.  This is an old old issue, see #10.
