### ISSUE TITLE
`dill` can't pickle `cairo.Matrix`, a seemingly simple pure Python class, and I can't figure out *why*.

### ISSUE THREAD

**Issue by bzm3r** [uqfoundation/dill#274]
Hi all, 

`dill` is awesome, I use it a lot. I found something it cannot pickle, and I figure out why. 

Cairo is a library that allows one to do 2D drawing. It is written in C but has Python wrappers. I use the `pycairo` wrapper. 

Consider this bit of code: 

```
import cairo #pycairo
import dill

x = cairo.Matrix()
print(x)

dill.detect.trace(True)

dill.dumps(cairo.Matrix())
```

I get the following output when running it on my machine: 

```
cairo.Matrix(1, 0, 0, 1, 0, 0)
Traceback (most recent call last):

  File "<ipython-input-1-5b940e6a48c7>", line 1, in <module>
    runfile('B:/numba-ncc/tests/cairo_pickling.py', wdir='B:/numba-ncc/tests')

  File "A:\anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "A:\anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "B:/numba-ncc/tests/cairo_pickling.py", line 14, in <module>
    dill.dumps(cairo.Matrix())

  File "A:\anaconda\lib\site-packages\dill\_dill.py", line 293, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)

  File "A:\anaconda\lib\site-packages\dill\_dill.py", line 286, in dump
    pik.dump(obj)

  File "A:\anaconda\lib\pickle.py", line 409, in dump
    self.save(obj)

  File "A:\anaconda\lib\pickle.py", line 496, in save
    rv = reduce(self.proto)

TypeError: can't pickle cairo.Matrix objects
```

Using `dill.detect.baditems` doesn't tell me more than this. What could the cause be? For my code, what I do as a workaround is to convert the Cairo matrix into a numpy array, and then pickle this numpy array and send it (the receiver has to then deconvert the matrix). 

But why should a seemingly simple, pure python object such as `cairo.Matrix` (https://www.cairographics.org/documentation/pycairo/3/reference/matrix.html) give `dill` issues?

**Comment by mmckerns** [comment]
@bzm3r: I'm going to assume from the lack of activity here that we have addressed your question.  Please reopen this ticket if you feel otherwise.
