### ISSUE TITLE
bdist_wheel upload failes for python3

### ISSUE THREAD

**Issue by thilo-maurer** [uqfoundation/dill#276]
After
```
pip3 download dill --no-binary :all:
```
then extracting the package, then
* build good
* upload failes, when using python3 (python2 is fine)

Reason is that in this projects's `setup.py` line 247, argument `classifiers` should be an array, not a tuple. Replacing `(` by `[` fixes the issue.

See log below:
```
root@host:/build/dill-0.2.8.2.tar.gz.extracted/dill-0.2.8.2# python3 setup.py bdist_wheel upload -r artifactory
running bdist_wheel
running build
running build_py
running build_scripts
installing to build/bdist.linux-ppc64le/wheel
running install
running install_lib
creating build/bdist.linux-ppc64le/wheel
creating build/bdist.linux-ppc64le/wheel/dill
copying build/lib/dill/settings.py -> build/bdist.linux-ppc64le/wheel/dill
copying build/lib/dill/source.py -> build/bdist.linux-ppc64le/wheel/dill
copying build/lib/dill/pointers.py -> build/bdist.linux-ppc64le/wheel/dill
copying build/lib/dill/_dill.py -> build/bdist.linux-ppc64le/wheel/dill
copying build/lib/dill/info.py -> build/bdist.linux-ppc64le/wheel/dill
copying build/lib/dill/__diff.py -> build/bdist.linux-ppc64le/wheel/dill
copying build/lib/dill/temp.py -> build/bdist.linux-ppc64le/wheel/dill
copying build/lib/dill/_objects.py -> build/bdist.linux-ppc64le/wheel/dill
creating build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_properties.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_detect.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/__main__.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_objects.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_recursive.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_nested.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_weakref.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_temp.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_check.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_module.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_functors.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_mixins.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_file.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/__init__.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_moduledict.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_diff.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_selected.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_classdef.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_extendpickle.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/tests/test_source.py -> build/bdist.linux-ppc64le/wheel/dill/tests
copying build/lib/dill/objtypes.py -> build/bdist.linux-ppc64le/wheel/dill
copying build/lib/dill/__init__.py -> build/bdist.linux-ppc64le/wheel/dill
copying build/lib/dill/detect.py -> build/bdist.linux-ppc64le/wheel/dill
running install_egg_info
running egg_info
writing dill.egg-info/PKG-INFO
writing dependency_links to dill.egg-info/dependency_links.txt
writing top-level names to dill.egg-info/top_level.txt
reading manifest file 'dill.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dill.egg-info/SOURCES.txt'
Copying dill.egg-info to build/bdist.linux-ppc64le/wheel/dill-0.2.8.2-py3.6.egg-info
running install_scripts
creating build/bdist.linux-ppc64le/wheel/dill-0.2.8.2.data
creating build/bdist.linux-ppc64le/wheel/dill-0.2.8.2.data/scripts
copying build/scripts-3.6/get_objgraph -> build/bdist.linux-ppc64le/wheel/dill-0.2.8.2.data/scripts
copying build/scripts-3.6/undill -> build/bdist.linux-ppc64le/wheel/dill-0.2.8.2.data/scripts
changing mode of build/bdist.linux-ppc64le/wheel/dill-0.2.8.2.data/scripts/get_objgraph to 755
changing mode of build/bdist.linux-ppc64le/wheel/dill-0.2.8.2.data/scripts/undill to 755
creating build/bdist.linux-ppc64le/wheel/dill-0.2.8.2.dist-info/WHEEL
creating '/build/dill-0.2.8.2.tar.gz.extracted/dill-0.2.8.2/dist/dill-0.2.8.2-py3-none-any.whl' and adding '.' to it
adding 'dill/__diff.py'
adding 'dill/__init__.py'
adding 'dill/_dill.py'
adding 'dill/_objects.py'
adding 'dill/detect.py'
adding 'dill/info.py'
adding 'dill/objtypes.py'
adding 'dill/pointers.py'
adding 'dill/settings.py'
adding 'dill/source.py'
adding 'dill/temp.py'
adding 'dill/tests/__init__.py'
adding 'dill/tests/__main__.py'
adding 'dill/tests/test_check.py'
adding 'dill/tests/test_classdef.py'
adding 'dill/tests/test_detect.py'
adding 'dill/tests/test_diff.py'
adding 'dill/tests/test_extendpickle.py'
adding 'dill/tests/test_file.py'
adding 'dill/tests/test_functors.py'
adding 'dill/tests/test_mixins.py'
adding 'dill/tests/test_module.py'
adding 'dill/tests/test_moduledict.py'
adding 'dill/tests/test_nested.py'
adding 'dill/tests/test_objects.py'
adding 'dill/tests/test_properties.py'
adding 'dill/tests/test_recursive.py'
adding 'dill/tests/test_selected.py'
adding 'dill/tests/test_source.py'
adding 'dill/tests/test_temp.py'
adding 'dill/tests/test_weakref.py'
adding 'dill-0.2.8.2.data/scripts/get_objgraph'
adding 'dill-0.2.8.2.data/scripts/undill'
adding 'dill-0.2.8.2.dist-info/top_level.txt'
adding 'dill-0.2.8.2.dist-info/WHEEL'
adding 'dill-0.2.8.2.dist-info/METADATA'
adding 'dill-0.2.8.2.dist-info/RECORD'
removing build/bdist.linux-ppc64le/wheel
running upload
Traceback (most recent call last):
  File "setup.py", line 285, in <module>
    exec(setup_code)
  File "<string>", line 187, in <module>
  File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 131, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/distutils/command/upload.py", line 64, in run
    self.upload_file(command, pyversion, filename)
  File "/usr/local/lib/python3.6/distutils/command/upload.py", line 162, in upload_file
    body.write(value)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by mmckerns** [comment]
fixed in 2e6a7a5fd61dedd9a3f3c0e165fc4add25361e7a
