### ISSUE TITLE
Problem dumping frames in sympy.physics.mechanics

### ISSUE THREAD

**Issue by kurosh-z** [uqfoundation/dill#279]
Hi, 
I use sympy to find equations of motion . I can dump and load any sympy expressions except those containing frames . A simple example would be  : 
 
```
import sympy as sm
import sympy.physics.mechanics as me
import dill 

frame = me.ReferenceFrame('frame')
 
with open('test.pkl', 'wb') as file :
    dill.dump(frame, file)

with open('test.pkl', 'rb') as file :
    frame_=dill.load(file)

    assert frame_== frame
```

dumping works just fine but I get problem loading it  : 
new__() takes exactly 4 arguments (2 given)

I was wondering if there is a workaround for this problem ?

![capture](https://user-images.githubusercontent.com/32224317/43821814-70238270-9aea-11e8-9ecf-f27090e65681.JPG)

**Comment by TJStienstra** [comment]
I just made more minimal reproducer, which shows more what is the actual problem:
```py
import dill


class CoordinateSymbol:
    def __new__(cls, frame, index):
        inst = super().__new__(cls)
        inst.id = (frame, index)
        return inst


class ReferenceFrame:
    def __init__(self, name):
        self.name = name
        self.varlist = [CoordinateSymbol(self, 1),
                        CoordinateSymbol(self, 2),
                        CoordinateSymbol(self, 3)]


frame = ReferenceFrame("N")
with open("test.pkl", "wb") as f:
    dill.dump(frame, f)
with open("test.pkl", "rb") as f:
    frame2 = dill.load(f)
```
This raises the following error:
```
Traceback (most recent call last):
  File "some_file.py", line 30, in <module>
    frame2 = dill.load(f)
  File "...\site-packages\dill\_dill.py", line 272, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "...\site-packages\dill\_dill.py", line 419, in load
    obj = StockUnpickler.load(self)
TypeError: __new__() missing 2 required positional arguments: 'frame' and 'index'
```
