### ISSUE TITLE
Can _handle_tasks in pool.py be made to pass back the exception?

### ISSUE THREAD

**Issue by lyssalivingston** [uqfoundation/dill#287]
While running this snippet of code (hopefully not **too** small):

```from pathos.pools import _ProcessPool as Pool
        ...
        self._pool = Pool(processes=self._psize, maxtasksperchild=4) # self._psize = 4
        ...
        c = getattr(module, name)
        LOG.debug('Instantiating class %s', str(c))
        task = c(cfg, tid)
        ...
        self._pool.apply_async(task.run, callback=self.acknowledge_message)
```

I have this traceback:

```Traceback (most recent call last):
  File "c:\programdata\conda\lib\site-packages\multiprocess\pool.py", line 350, in _handle_tasks
    put(task)
  File "c:\programdata\conda\lib\site-packages\dill\_dill.py", line 293, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "c:\programdata\conda\lib\site-packages\dill\_dill.py", line 286, in dump
    pik.dump(obj)
  File "c:\programdata\conda\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "c:\programdata\conda\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\programdata\conda\lib\pickle.py", line 568, in save_tuple
    save(element)
  File "c:\programdata\conda\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\programdata\conda\lib\site-packages\dill\_dill.py", line 1072, in save_instancemethod0
obj.im_class), obj=obj)
  File "c:\programdata\conda\lib\pickle.py", line 401, in save_reduce
    save(args)
  File "c:\programdata\conda\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\programdata\conda\lib\pickle.py", line 554, in save_tuple
    save(element)
  File "c:\programdata\conda\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "c:\programdata\conda\lib\pickle.py", line 425, in save_reduce
    save(state)
File "c:\programdata\conda\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\programdata\conda\lib\site-packages\dill\_dill.py", line 893, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "c:\programdata\conda\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "c:\programdata\conda\lib\pickle.py", line 687, in _batch_setitems
save(v)
  File "c:\programdata\conda\lib\pickle.py", line 306, in save
    rv = reduce(self.proto)
TypeError: 'Box' object is not callable
```

It took me a while to get to this error, since I had to put in debugging into pool.py to figure out what was going on. Is there any chance of getting the exception passed back? The task that is supposed to be executing just hangs - it never gets any further after this, but I also don't get an exception to do anything with. If processing an exception is not correct, then what should I be doing? Thanks.

**Comment by lyssalivingston** [comment]
And because I was really tired when I wrote this, I figured I'd add more about the system specs:

- Windows Server 2012 R2 Standard
- python 2.7.15
- multiprocess==0.70.6.1
- dill==0.2.8.2
- conda==4.6.0b1

multiprocess was installed with Christoph Gohlke Unofficial Windows Binaries:  [https://www.lfd.uci.edu/~gohlke/pythonlibs/#multiprocess](https://www.lfd.uci.edu/~gohlke/pythonlibs/#multiprocess), file multiprocess‑0.70.6.1‑cp27‑cp27m‑win_amd64.whl. The line numbers in the traceback are off from the actual lines in pool.py because I had put in debugging, specifically to get the traceback.

Please let me know if there is any more information I can add to this. Thanks for your help.

**Comment by mmckerns** [comment]
@lyssalivingston: sorry for the slow response.  This isn't really a `dill` issue... it's more of a `multiprocess` question.  I'll answer what I can here, however.

Just focusing on `dill`, you can pickle two of the three things necessary to return the relevant error info:
```
>>> import sys 
>>> try:
...   a = foobar
... except:
...   a = sys.exc_info()
... 
>>> import dill
>>> dill.copy(a[0])
<type 'exceptions.NameError'>
>>> dill.copy(a[1])
NameError("name 'foobar' is not defined",)
>>> dill.copy(a[2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python2.7/site-packages/dill/_dill.py", line 239, in copy
    return loads(dumps(obj, *args, **kwds))
  File "/Users/mmckerns/lib/python2.7/site-packages/dill/_dill.py", line 293, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/Users/mmckerns/lib/python2.7/site-packages/dill/_dill.py", line 286, in dump
    pik.dump(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
TypeError: can't pickle traceback objects
>>> 
```
However, if you are using `pathos`, there's a nice utility that enables you to catch the traceback:
```
>>> import pathos    
>>> try:
...   a = dill.copy(a[2])
... except:
...   a = pathos.util.print_exc_info()
... 
>>> print(a)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/mmckerns/lib/python2.7/site-packages/dill/_dill.py", line 239, in copy
    return loads(dumps(obj, *args, **kwds))
  File "/Users/mmckerns/lib/python2.7/site-packages/dill/_dill.py", line 293, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/Users/mmckerns/lib/python2.7/site-packages/dill/_dill.py", line 286, in dump
    pik.dump(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
TypeError: can't pickle traceback objects

>>> 
```
So, if you wanted to get the exception passed back... you'd need to have your run function use a try/except block, with an alternate return of the exception if it occurs (using some combination of the above).  `multiprocess` doesn't have built-in error recovery for the `Pool` objects -- `pathos` might, but I don't *think* it does.  You can pretty easily add this functionality to your run function with the above however.

Please close the ticket if this answers your question.

**Comment by mmckerns** [comment]
Your error seems to be because you are trying to call a `Box` object, and it doesn't have a `__call__` method.  If you use the approach I've outlined above, you can get your traceback and error objects back from the spawned child process.  I'm not sure what else you are asking.  Your code snippet is not an minimal encapsulated one, so I can't do anything else with it than answer the more general issue of getting back your traceback and error objects.

**Comment by lyssalivingston** [comment]
Sorry it's taken so long to respond, but I have been snowed under with
work. I do have all the code in several nested try/except block. The
apply_async() is itself in a try/except, and that task.run() ultimately
calls the run method of the class that has been instantiated, which again
is in a try/except block. Neither catch the exception: the process just
hangs. However, I will try pathos.util.print_exc_info() and see what I can
get with that. Thanks for your reply and your time.

Lyssa

**Comment by lyssalivingston** [comment]
Not sure if I should close this and start a new request, so please let me know what you would like. This seems to be at the heart of the problem:

```(base) C:\ProgramData\VZW\atoll-automation\vzauto>python -i
Python 2.7.15 |Anaconda, Inc.| (default, Dec 10 2018, 21:57:18) [MSC v.1500 64 b
it (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from box import Box
>>> from dill import dumps
>>> dumps(Box(default_box=True, box_it_up=True))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\conda\lib\site-packages\dill\_dill.py", line 294, in dump
s
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "C:\ProgramData\conda\lib\site-packages\dill\_dill.py", line 287, in dump

    pik.dump(obj)
  File "C:\ProgramData\conda\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\ProgramData\conda\lib\pickle.py", line 306, in save
    rv = reduce(self.proto)
TypeError: 'Box' object is not callable
>>> from pickle import dumps
>>> dumps(Box(default_box=True, box_it_up=True))
"ccopy_reg\n_reconstructor\np0\n(cbox\nBox\np1\ncdill._dill\n_load_type\np2\n(S'DictType'\np3\ntp4\nRp5\n(dp6\ntp7\nRp8\n(dp9\nS'_box_config'\np10\n(dp11\nS'conversion_box'\np12\nI01\nsS'default_box'\np13\nI01\nsS'modify_tuples_box'\np14\nI00\nsS'__box_heritage'\np15\nNsS'frozen_box'\np16\nI00\nsS'__converted'\np17\nc__builtin__\nset\np18\n((lp19\ntp20\nRp21\nsS'box_duplicates'\np22\nS'ignore'\np23\nsS'__created'\np24\nI01\nsS'ordered_box'\np25\nI00\nsS'camel_killer_box'\np26\nI00\nsS'box_safe_prefix'\np27\nS'x'\np28\nsS'default_box_attr'\np29\ng1\nssb."
>>>
```
This is using dill==0.2.9.

In my original message, I said that I wanted the exception from _handle_tasks(). This is because instantiating the Box object occurs in `__init__()` while pickling the Box object occurs in the multiprocess code, before it ever gets to `task.run()`. Therefore, there is no way for me to catch the exception, because it is not in code that I have access to.

The use of the Box package is by a developer who does not want to stop using it; that is, this is not something I wrote and I am unfamiliar with the Box package. I am trying to use the developer's code as is and integrate it into a multiprocess Process pool. Thus, I don't know if it's a Box problem and dill is doing the right thing while pickle is not, or if it's a dill bug.

I hope this clarifies what I am trying to do. Thanks for your help.

**Comment by lyssalivingston** [comment]
Also, https://github.com/cdgriffith/Box/issues/64

**Comment by lyssalivingston** [comment]
I investigated some more into this issue and discovered that Box only supports protocol 0 for pickling while dill uses protocol 2. So the developer has a workaround and can continue to use Box as part of the code. Thanks for your help.
