### ISSUE TITLE
Can't pickle SSLContext objects

### ISSUE THREAD

**Issue by seanthegeek** [uqfoundation/dill#308]
```
Python 3.6.7 (default, Oct 21 2018, 08:08:16)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> import dill
>>> ssl_context = ssl.create_default_context()
>>> pickled = dill.dumps(ssl_context)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/dill/_dill.py", line 294, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/usr/local/lib/python3.6/dist-packages/dill/_dill.py", line 287, in dump
    pik.dump(obj)
  File "/usr/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/usr/lib/python3.6/pickle.py", line 496, in save
    rv = reduce(self.proto)
TypeError: can't pickle SSLContext objects
```

**Comment by NehaBisht** [comment]
Hi, did you get a solution to this error? I am getting a similar error.

**Comment by zigzagcai** [comment]
I also met this error. Could anyone give some insight about how to fix this?

**Comment by iafuad** [comment]
I'm also facing the same error when trying to pickle an instance of a custom class. FYI, it is using HTTP2 `httpx.AsyncClient` as a client for making requests to an API.
