### ISSUE TITLE
NameError: name 'msg' is not defined, getsource on lambda

### ISSUE THREAD

**Issue by dj-axl** [uqfoundation/dill#327]
Python 3.7.4 64-bit

import dill
square = lambda x: x**2
dill.source.getsource(square)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Python37\lib\site-packages\dill\source.py", line 354, in getsource
    lines, lnum = getsourcelines(object, enclosing=enclosing)
  File "C:\Python\Python37\lib\site-packages\dill\source.py", line 325, in getsourcelines
    code, n = getblocks(object, lstrip=lstrip, enclosing=enclosing, locate=True)
  File "C:\Python\Python37\lib\site-packages\dill\source.py", line 251, in getblocks
    lines, lnum = findsource(object)
  File "C:\Python\Python37\lib\site-packages\dill\source.py", line 129, in findsource
    raise IOError(msg)
NameError: name 'msg' is not defined

**Comment by mmckerns** [comment]
whoops looks like a typo...

**Comment by mmckerns** [comment]
Should be fixed with https://github.com/uqfoundation/dill/commit/6dfe018a43c88649582cc343dc657127fe554833
