### ISSUE TITLE
I couldn't dump a class within `code.InteractiveInterpreter`

### ISSUE THREAD

**Issue by octaltree** [uqfoundation/dill#352]
Does dill supports only `"__main__"`? I tried dumping class `Foo` within `code.InteractiveInterpreter`, I got message "builtins.Foo not found". Could you check this, please?
```
import dill
import sys
from code import InteractiveInterpreter

print(sys.version) # 3.7.4 (default, Oct  4 2019, 06:57:26)\n[GCC 9.2.0]
print(dill.__version__)  # 0.3.1.1
print(__name__) # __main__

class Foo:
    pass
b = dill.dumps(Foo)
print(b) # bytes value

i = InteractiveInterpreter({})
i.runsource('print(globals())', symbol='exec') # {'__builtins__': {'__name__': 'builtins', '__doc_
i.runsource('import dill', symbol='exec')
i.runsource('class Foo:\n    pass', symbol='exec')
i.runsource('print(dill.dumps(Foo))', symbol='exec')
#Traceback (most recent call last):
#  File "<input>", line 1, in <module>
#  File "/usr/lib/python3.7/site-packages/dill/_dill.py", line 265, in dumps
#    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
#  File "/usr/lib/python3.7/site-packages/dill/_dill.py", line 259, in dump
#    Pickler(file, protocol, **_kwds).dump(obj)
#  File "/usr/lib/python3.7/site-packages/dill/_dill.py", line 445, in dump
#    StockPickler.dump(self, obj)
#  File "/usr/lib/python3.7/pickle.py", line 437, in dump
#    self.save(obj)
#  File "/usr/lib/python3.7/pickle.py", line 504, in save
#    f(self, obj) # Call unbound method with explicit self
#  File "/usr/lib/python3.7/site-packages/dill/_dill.py", line 1356, in save_type
#    StockPickler.save_global(pickler, obj)
#  File "/usr/lib/python3.7/pickle.py", line 960, in save_global
#    (obj, module_name, name)) from None
#_pickle.PicklingError: Can't pickle <class 'Foo'>: it's not found as builtins.Foo

i = InteractiveInterpreter({'__name__': '__main__', 'answer': b})
i.runsource('import dill', symbol='exec')
i.runsource('class Foo:\n    pass', symbol='exec')
i.runsource('print(answer == dill.dumps(Foo))', symbol='exec') # True
```

**Comment by matsjoyce** [comment]
Dill (currently) stores things like classes in two ways: by reference or by storing the entire thing. The switch is determined by the classes module: if the module is `__main__`, it gets stored, otherwise it is referenced. So setting `__name__` appropriately is the current fix.

**Comment by octaltree** [comment]
I was using `InteractiveInterpreter({"__name__": "__main __"})`, when dumping the function, `globs` that is args of `_create_function` would not match `obj == pickler._main.__dict__` in `save_module_dict` and finally saved with `save_dict`.

```
import __main__ as _main_module
```
```
        self._main = _main_module
```

If you provide an interface to assign here, it seems to be solved, but can you do it?

**Comment by octaltree** [comment]
Since `dill.Pickler` was exported, I noticed that it can be solved by inheriting it.

**Comment by octaltree** [comment]
Please close because I decided to use IPython instead of `InteractiveInterpter`.
A function`.__globals__` saved correctly in IPyton.

**Comment by matsjoyce** [comment]
You should have a close button under the comments box IIRC.
