### ISSUE TITLE
TypeError: abstract class on BigEndian

### ISSUE THREAD

**Issue by azouhr** [uqfoundation/dill#361]
During build of python-dill on s390x, I get the following error:
```
[    3s] + python3 tests/__main__.py
[    3s] Traceback (most recent call last):
[    3s]   File "tests/test_selected.py", line 43, in <module>
[    3s]     load_types(pickleable=True,unpickleable=False)
[    3s]   File "/home/abuild/rpmbuild/BUILDROOT/python-dill-0.3.1.1-0.s390x/usr/lib/python3.8/site-packages/dill/__init__.py", line 77, in load_types
[    3s]     from . import _objects
[    3s]   File "/home/abuild/rpmbuild/BUILDROOT/python-dill-0.3.1.1-0.s390x/usr/lib/python3.8/site-packages/dill/_objects.py", line 219, in <module>
[    3s]     a['BigEndianStructureType'] = ctypes.BigEndianStructure()
[    3s] TypeError: abstract class
```

After removing the entry in dill/_objects.py, everything works:
```
--- dill/_objects.py.orig       2020-04-22 10:18:37.450580898 +0200
+++ dill/_objects.py    2020-04-22 10:19:12.510580898 +0200
@@ -216,13 +216,6 @@
     a['CSizeTType'] = ctypes.c_size_t()
     a['CLibraryLoaderType'] = ctypes.cdll
     a['StructureType'] = _Struct
-    if not IS_PYPY:
-        a['BigEndianStructureType'] = ctypes.BigEndianStructure()
-#NOTE: also LittleEndianStructureType and UnionType... abstract classes
-#NOTE: remember for ctypesobj.contents creates a new python object
-#NOTE: ctypes.c_int._objects is memberdescriptor for object's __dict__
-#NOTE: base class of all ctypes data types is non-public _CData
-
 try: # python 2.6
     import fractions
     import number
```
Since this is not pypy, I am unsure if this is needed at all. The last version that I know worked on s390x was 0.2.7.1

**Comment by jayvdb** [comment]
openSUSE s390x and ppc64 builds are failing because of this.  See https://build.opensuse.org/package/show/devel:languages:python/python-dill

**Comment by mmckerns** [comment]
it appears that there are now restrictions on building a abstract class with `__init__`.  I'll comment this out for now.

**Comment by mmckerns** [comment]
Should be resolved by: https://github.com/uqfoundation/dill/commit/07e24913e88dfe26448226f9cfd1ee6cf5c2a760.
Reopen if that's not the case.
