### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by 3fon3fonov** [uqfoundation/dill#380]
I do not understand what is going one with this error! I am trying to load a dill dump made on 
a server to my local machine. 

to save the dump:

```
    file_ses = open("target_out.ses", "wb")
    dill.dump(fit, file_ses)
    file_ses.close()

```

to load back:

```
        file = open(str(sys.argv[2]), "rb")
        fit = dill.load(file)
        file.close()   
```

And the error:

tito@terminator:~//MCMC$ python3 make_stab_cornerplot.py -ses target_out.ses 
Traceback (most recent call last):
  File "make_stab_cornerplot.py", line 56, in <module>
    fit = dill.load(file_pi2)
  File "/usr/local/lib/python3.6/dist-packages/dill/_dill.py", line 270, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/usr/local/lib/python3.6/dist-packages/dill/_dill.py", line 473, in load
    obj = StockUnpickler.load(self)
OSError: [Errno 9] Bad file descriptor

I do not have the problem on the server machine.

Any ideas on how to debug?

**Comment by 3fon3fonov** [comment]
Any ideas on this? This bug is killing me.... :/

**Comment by mmckerns** [comment]
I don't have enough information to give you a decent response, unfortunately.  For example, are the version of `python`, and `dill`, and whatever other dependencies you are using identical on both machines?

Also, did you try modifying `dill.settings['fmode']` to change how `dill` handles files?

**Comment by 3fon3fonov** [comment]
Sorry for the late reply!

This problem just re-emerged and I just saw your suggestion. 

Are you suggesting to fo:

```
$ import dill
$ dill.settings['fmode']
```

I will try and will post ASAP.

**Comment by mmckerns** [comment]
You will need all dependencies installed on both machines, including `python` and `dill`.  It would also help to know which versions you are using.  If they are all identical, then you might want to try changing the value of `dill.settings['fmode']`
