### ISSUE TITLE
Dill trigger __init_subclass__ multiple times

### ISSUE THREAD

**Issue by Conchylicultor** [uqfoundation/dill#381]
I'm not sure how `dill` is implemented, but it seems to break `__init_subclass__` by calling it on already existing class:

Tested with Python 3.8, Dill version: 3.2.0.

Example to reproduce the issue:

```python
import dill
import pickle  # Import pickle, just for comparison


class A:
  subclasses = {}

  def __init_subclass__(cls):
    if cls.__name__ in cls.subclasses:
      raise ValueError(f'{cls.__name__} already exists')
    cls.subclasses[cls.__name__] = cls


class B(A):
  pass


pickle.loads(pickle.dumps(B())) # Works
dill.loads(dill.dumps(B())) # Raise ValueError: B already exists
```

Full stacktrace:
```
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    dill.loads(dill.dumps(B())) # Raise ValueError: B already exists
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dill/_dill.py", line 275, in loads
    return load(file, ignore, **kwds)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dill/_dill.py", line 270, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dill/_dill.py", line 473, in load
    obj = StockUnpickler.load(self)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dill/_dill.py", line 583, in _create_type
    return typeobj(*args)
  File "main.py", line 10, in __init_subclass__
    raise ValueError(f'{cls.__name__} already exists')
ValueError: B already exists
```

**Comment by Conchylicultor** [comment]
I believe this might only happen for object which are created in the `__main__` module.
