### ISSUE TITLE
dill can't pickle subprocess.Popen objects, and fails ungracefully

### ISSUE THREAD

**Issue by dkogan** [uqfoundation/dill#391]
Hi. I'm using the latest 'dill' from git. I have this demo program:

```python
import dill
import subprocess
p = subprocess.Popen('cat', stdin=subprocess.PIPE)

dill.dump_session('/tmp/tst.dill')
```

It does this:

```
Traceback (most recent call last):
  File "/tmp/tst.py", line 10, in <module>
    dill.dump_session('/tmp/tst.dill')
  File "/home/dima/projects/dill/build/lib/dill/_dill.py", line 359, in dump_session
    pickler.dump(main)
  File "/home/dima/projects/dill/build/lib/dill/_dill.py", line 454, in dump
    StockPickler.dump(self, obj)
  File "/usr/lib/python3.8/pickle.py", line 485, in dump
    self.save(obj)
  File "/usr/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/dima/projects/dill/build/lib/dill/_dill.py", line 1326, in save_module
    pickler.save_reduce(_import_module, (obj.__name__,), obj=obj,
  File "/usr/lib/python3.8/pickle.py", line 715, in save_reduce
    save(state)
  File "/usr/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/dima/projects/dill/build/lib/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.8/pickle.py", line 969, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.8/pickle.py", line 995, in _batch_setitems
    save(v)
  File "/usr/lib/python3.8/pickle.py", line 601, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.8/pickle.py", line 715, in save_reduce
    save(state)
  File "/usr/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/dima/projects/dill/build/lib/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.8/pickle.py", line 969, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.8/pickle.py", line 995, in _batch_setitems
    save(v)
  File "/usr/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/dima/projects/dill/build/lib/dill/_dill.py", line 1039, in save_file
    f = _save_file(pickler, obj, open)
  File "/home/dima/projects/dill/build/lib/dill/_dill.py", line 1013, in _save_file
    position = obj.tell()
OSError: [Errno 29] Illegal seek
```

I still get a `/tmp/tst.dill` on disk, but it doesn't contain anything valid. It makes perfect sense to not be able to pickle live subprocesses, but in a perfect world it would throw a warning, and still write out a valid dill that's missing that one object.

Thanks!

**Comment by TheBigFailure** [comment]
Hey, @dkogan, I was, long story short, making a system to log all local and global variables upon a server exception and was using dill to pickle the values, and received a similar error  `UnsupportedOperation: seek` when calling `dill.pickles` for value. I unfortunately haven't been able to replicate the bug, so I'm not sure what value was causing this error (also foolishly instinctively cleared the terminal before I could copy the traceback), but I'm beginning to believe this might be a recurring bug?

**Comment by mmckerns** [comment]
I can reproduce this error.  It seems to stem from a `BufferedWriter` object.

```
Python 3.8.19 (default, Mar 22 2024, 01:55:18) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> dill.detect.trace(True)
>>> import subprocess
>>> p = subprocess.Popen('cat', stdin=subprocess.PIPE)
>>> s = dill.dumps(p)
┬ T4: <class 'subprocess.Popen'>
└ # T4 [23 B]
┬ D2: <dict object at 0x0100d08780>
├┬ Lo: <unlocked _thread.lock object at 0x100d09ba0>
│├┬ F2: <function _create_lock at 0x10145aee0>
││└ # F2 [30 B]
│└ # Lo [35 B]
├┬ Fi: <_io.BufferedWriter name=4>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python3.8/site-packages/dill/_dill.py", line 280, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "/Users/mmckerns/lib/python3.8/site-packages/dill/_dill.py", line 252, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/Users/mmckerns/lib/python3.8/site-packages/dill/_dill.py", line 420, in dump
    StockPickler.dump(self, obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pickle.py", line 487, in dump
    self.save(obj)
  File "/Users/mmckerns/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/Users/mmckerns/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python3.8/site-packages/dill/_dill.py", line 1217, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/Users/mmckerns/lib/python3.8/site-packages/dill/_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python3.8/site-packages/dill/_dill.py", line 1366, in save_file
    f = _save_file(pickler, obj, open)
  File "/Users/mmckerns/lib/python3.8/site-packages/dill/_dill.py", line 1341, in _save_file
    position = obj.tell()
OSError: [Errno 29] Illegal seek
```

**Comment by TheBigFailure** [comment]
Yeah this should not be happening, especially not for `dill.pickles` given it's a checking function. I can recreate the behaviour on Python 3.12.4 on Linux (Ubuntu 22.04.4 LTS).

```python
Python 3.12.4 (main, Jun  8 2024, 18:29:57) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> dill.detect.trace(True)
>>> import subprocess
>>> p = subprocess.Popen('cat', stdin=subprocess.PIPE)
>>> s = dill.dumps(p)
┬ T4: <class 'subprocess.Popen'>
└ # T4 [23 B]
┬ D2: <dict object at 0x7f061397a940>
├┬ Lo: <unlocked _thread.lock object at 0x7f061397a600>
│├┬ F2: <function _create_lock at 0x7f0613ab1120>
││└ # F2 [30 B]
│└ # Lo [35 B]
├┬ Fi: <_io.BufferedWriter name=4>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anony/.local/lib/python3.12/site-packages/dill/_dill.py", line 280, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anony/.local/lib/python3.12/site-packages/dill/_dill.py", line 252, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/home/anony/.local/lib/python3.12/site-packages/dill/_dill.py", line 420, in dump
    StockPickler.dump(self, obj)
  File "/usr/lib/python3.12/pickle.py", line 481, in dump
    self.save(obj)
  File "/home/anony/.local/lib/python3.12/site-packages/dill/_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.12/pickle.py", line 597, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.12/pickle.py", line 711, in save_reduce
    save(state)
  File "/home/anony/.local/lib/python3.12/site-packages/dill/_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.12/pickle.py", line 554, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "/home/anony/.local/lib/python3.12/site-packages/dill/_dill.py", line 1217, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.12/pickle.py", line 966, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.12/pickle.py", line 990, in _batch_setitems
    save(v)
  File "/home/anony/.local/lib/python3.12/site-packages/dill/_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.12/pickle.py", line 554, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "/home/anony/.local/lib/python3.12/site-packages/dill/_dill.py", line 1366, in save_file
    f = _save_file(pickler, obj, open)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anony/.local/lib/python3.12/site-packages/dill/_dill.py", line 1341, in _save_file
    position = obj.tell()
               ^^^^^^^^^^
OSError: [Errno 29] Illegal seek
```
Not the exact error I got, but I presume it's due to the same root cause? I think I remember the `obj.tell()` somewhere in the traceback I originally got for the `UnsupportedOperation: seek` I got.

**Comment by mmckerns** [comment]
@TheBigFailure: Thanks, but I disagree with you with regard to `dill.pickles`.  If you look at the docs, it catches only `exceptions = (TypeError, AssertionError, NotImplementedError, PicklingError, UnpicklingError)` by default. If you want to guard against all ` exceptions = (Exception,)`, then use `dill.pickles(p, safe=True)`.  If that throws an error, it should be fixed separately from `dumps`.
