### ISSUE TITLE
Cannot dill.copy cv2.TrackerKCF object

### ISSUE THREAD

**Issue by ATrackerLearner** [uqfoundation/dill#415]
Hi, 

### Context

I am developping a tracking algorithm from video stream. I have several people identified from an input video stream that I would like to track individually, frame to frame. So I use the module [OpenCV-python](https://github.com/opencv/opencv-python) to track one person from one frame to the next one. One tracker object is used for each person. Sometimes, I have dozens of people on a frame. Each tracking is done on the same CPU. I would like to do a multiprocess tracking.

**Example:**
I have 20 tracked people on the frame and I have 4 CPU. I would like to track 5 people per CPU instead of tracking 20 people on a single CPU (default behaviour). So I make a pool with 4 available proccesses that parrallelize my tracking task.

I realized that `cv2.TrackerKCF` cannot be pickled. **Although I can pickle my custom objects thanks to dill** 

### Error

I would like to be able to pickle an `cv2.TrackerKCF` object.
**Step to reproduce:**
```
import dill, cv2

dill.copy( cv2.TrackerKCF() )
```
**Logs:**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/muffie/code/ksm/code/env/lib/python3.8/site-packages/dill/_dill.py", line 264, in copy
    return loads(dumps(obj, *args, **kwds), ignore=ignore)
  File "/home/muffie/code/ksm/code/env/lib/python3.8/site-packages/dill/_dill.py", line 304, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "/home/muffie/code/ksm/code/env/lib/python3.8/site-packages/dill/_dill.py", line 276, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/home/muffie/code/ksm/code/env/lib/python3.8/site-packages/dill/_dill.py", line 498, in dump
    StockPickler.dump(self, obj)
  File "/usr/lib/python3.8/pickle.py", line 485, in dump
    self.save(obj)
  File "/usr/lib/python3.8/pickle.py", line 576, in save
    rv = reduce(self.proto)
TypeError: cannot pickle 'cv2.TrackerKCF' object
```

I think that it is caused by [OpenCV-python](https://github.com/opencv/opencv-python) written in C++ and its translation in Python.
I would like to know if there is a work around for this case.

### Workaround attempt:
I tried to wrap my `cv2.TrackerKCF` in another object, it doesn't work.
```
import cv2, dill
class Tracker:
  def __init__(self, tracker : cv2.TrackerKCF):
    self.tracker = tracker

dill.copy( Tracker( cv2.TrackerKCF() )  )
```

I'm not a multiprocessing expert at all, I hope I didn't miss any important point.

Thanks for reading,

Mathias.

**Comment by GeorgeVJose** [comment]
Have anyone found a solution to this? Love to hear it if you've found one... Thanks

**Comment by mmckerns** [comment]
Sorry for the lack of a response here.  You could turn on `dill.detect.trace(True)` to trace the pickling path and try to see exactly where it fails.  However, I expect you are right in that it hits a C++ object and fails to serialize because of that.  It might be possible to build your own tracker class with a custom `__reduce__` method that tells `dill` how to save the state of a tracker.
