### ISSUE TITLE
Recursively pickling a function that references `os` fails in Python 3.9

### ISSUE THREAD

**Issue by benesch** [uqfoundation/dill#417]
On my machine (macOS), the following fails with Python 3.9.6:

```py
import dill
import os
import pickle

def func():
    return os.name

print(dill.dumps(func, recurse=True))
```

```
Traceback (most recent call last):
  File "/Users/benesch/Sites/dill-bug/bug.py", line 8, in <module>
    print(dill.dumps(func, recurse=True))
  File "/private/tmp/venv/lib/python3.9/site-packages/dill/_dill.py", line 304, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "/private/tmp/venv/lib/python3.9/site-packages/dill/_dill.py", line 276, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/private/tmp/venv/lib/python3.9/site-packages/dill/_dill.py", line 498, in dump
    StockPickler.dump(self, obj)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 487, in dump
    self.save(obj)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/private/tmp/venv/lib/python3.9/site-packages/dill/_dill.py", line 1493, in save_function
    pickler.save_reduce(_create_function, (obj.__code__,
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 692, in save_reduce
    save(args)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 901, in save_tuple
    save(element)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/private/tmp/venv/lib/python3.9/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 1002, in _batch_setitems
    save(v)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/private/tmp/venv/lib/python3.9/site-packages/dill/_dill.py", line 1375, in save_module
    pickler.save_reduce(_import_module, (obj.__name__,), obj=obj,
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 717, in save_reduce
    save(state)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/private/tmp/venv/lib/python3.9/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/private/tmp/venv/lib/python3.9/site-packages/dill/_dill.py", line 1519, in save_function
    StockPickler.save_global(pickler, obj, name=name)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 1070, in save_global
    raise PicklingError(
_pickle.PicklingError: Can't pickle <function _fscodec.<locals>.fsencode at 0x102861700>: it's not found as os._fscodec.<locals>.fsencode
```

But it work just fine under Python 3.8.11, weirdly enough.

**Comment by mmckerns** [comment]
I'm unable to reproduce the issue.  
```
Python 3.9.6 (default, Jul  3 2021, 08:33:50) 
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> import os
>>> import pickle
>>> 
>>> def func():
...     return os.name
... 
>>> print(dill.dumps(func, recurse=True))
b'\x80\x04\x95\xab\x00\x00\x00\x00\x00\x00\x00\x8c\ndill._dill\x94\x8c\x10_create_function\x94\x93\x94(h\x00\x8c\x0c_create_code\x94\x93\x94(K\x00K\x00K\x00K\x00K\x01KCC\x06t\x00j\x01S\x00\x94N\x85\x94\x8c\x02os\x94\x8c\x04name\x94\x86\x94)\x8c\x07<stdin>\x94\x8c\x04func\x94K\x01C\x02\x00\x01\x94))t\x94R\x94}\x94\x8c\x02os\x94h\x00\x8c\x0e_import_module\x94\x93\x94h\x07\x85\x94R\x94sh\x0bNN}\x94Nt\x94R\x94.'
>>> dill.__version__
'0.3.4'
```

What is your version of `dill`?  Also, please try again, but after:
`>>> dill.detect.trace(True)
`

**Comment by benesch** [comment]
Thanks very much for looking into this. I think it is something particular about macOS. I can't reproduce on Linux. This is dill v0.3.4.

Here's the output again with tracing enabled: https://gist.github.com/benesch/7053016d4f83282a99c029e0ae358ff8

**Comment by mmckerns** [comment]
I've replaced your environment as best as I can tell (also on a Mac), here's what I get:
```
F1: <function func at 0x108c38160>
F2: <function _create_function at 0x10919a0d0>
# F2
Co: <code object func at 0x108b370e0, file "<stdin>", line 1>
F2: <function _create_code at 0x10919a160>
# F2
# Co
D2: <dict object at 0x109212e80>
M2: <module 'os' from '/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py'>
F2: <function _import_module at 0x10919aca0>
# F2
# M2
# D2
D2: <dict object at 0x108c32200>
# D2
# F1
b'\x80\x04\x95\xab\x00\x00\x00\x00\x00\x00\x00\x8c\ndill._dill\x94\x8c\x10_create_function\x94\x93\x94(h\x00\x8c\x0c_create_code\x94\x93\x94(K\x00K\x00K\x00K\x00K\x01KCC\x06t\x00j\x01S\x00\x94N\x85\x94\x8c\x02os\x94\x8c\x04name\x94\x86\x94)\x8c\x07<stdin>\x94\x8c\x04func\x94K\x01C\x02\x00\x01\x94))t\x94R\x94}\x94\x8c\x02os\x94h\x00\x8c\x0e_import_module\x94\x93\x94h\x07\x85\x94R\x94sh\x0bNN}\x94Nt\x94R\x94.'
```

**Comment by mmckerns** [comment]
The difference is:

`M1: <module 'os' from '/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py'>`
versus my
`M2: <module 'os' from '/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py'>`.

I'll see if I can figure out why your `os` module is getting picked up differently.

**Comment by mmckerns** [comment]
What do you get for the following?:
```
>>> import os
>>> obj = os
>>> hasattr(obj, "__file__")
True
>>> names = ["base_prefix", "base_exec_prefix", "exec_prefix", "prefix", "real_prefix"]
>>> import sys
>>> builtin_mod = any(obj.__file__.startswith(os.path.normpath(getattr(sys, name))) for name in names if hasattr(sys, name))
>>> builtin_mod
True
>>> import importlib.machinery
>>> EXTENSION_SUFFIXES = tuple(importlib.machinery.EXTENSION_SUFFIXES)
>>> EXTENSION_SUFFIXES
('.cpython-36m-darwin.so', '.abi3.so', '.so')
>>> builtin_mod = (builtin_mod or obj.__file__.endswith(EXTENSION_SUFFIXES) or 'site-packages' in obj.__file__)
>>> builtin_mod
True
```

**Comment by benesch** [comment]
Weird! 

```
>>> import os
>>> obj = os
>>> hasattr(obj, "__file__")
True
>>> names = ["base_prefix", "base_exec_prefix", "exec_prefix", "prefix", "real_prefix"]
>>> import sys
>>> builtin_mod = any(obj.__file__.startswith(os.path.normpath(getattr(sys, name))) for name in names if hasattr(sys, name))
>>> builtin_mod
False
>>> import importlib.machinery
>>> EXTENSION_SUFFIXES = tuple(importlib.machinery.EXTENSION_SUFFIXES)
>>> EXTENSION_SUFFIXES
('.cpython-39-darwin.so', '.abi3.so', '.so')
>>> builtin_mod = (builtin_mod or obj.__file__.endswith(EXTENSION_SUFFIXES) or 'site-packages' in obj.__file__)
>>> builtin_mod
False
```

**Comment by benesch** [comment]
I installed via Homebrew (`brew install python`), if that is interesting

**Comment by mmckerns** [comment]
What do you get for the following:
```
>>> import os
>>> import sys
>>> os.__file__
'/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py'
```
at least one of the following should start the same as the above
```
>>> os.path.normpath(sys.base_prefix)
'/opt/local/Library/Frameworks/Python.framework/Versions/3.9'
>>> os.path.normpath(sys.base_exec_prefix)
'/opt/local/Library/Frameworks/Python.framework/Versions/3.9'
>>> os.path.normpath(sys.exec_prefix)
'/opt/local/Library/Frameworks/Python.framework/Versions/3.9'
>>> os.path.normpath(sys.prefix)
'/opt/local/Library/Frameworks/Python.framework/Versions/3.9'
>>> os.path.normpath(sys.real_prefix)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sys' has no attribute 'real_prefix'
```
I'm assuming the start of the paths don't match.  We'll have to figure out why.  The code is a bit weak in determining if the module is to be treated as a builtin or not, as for a few modules like `os` it depends on the install path.  So, if there's something weird in how it was installed, it might not work correctly.  The paths above should at least have one match.

**Comment by benesch** [comment]
Cool, that helps a lot. I’m out of pocket for the rest of the weekend but
will get back to you with the results of the investigation Monday,
hopefully.

Thanks very much for looking into this!

**Comment by benesch** [comment]
Oh, ok, this turns out to be easy. With Homebrew, the compiled `base_prefix` is symlinked to the actual installation directory:

```
benesch@langur$ python
Python 3.9.6 (default, Jun 29 2021, 05:25:02) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.base_prefix
'/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9'

benesch@langur$ ls -l /usr/local/opt/python@3.9
lrwxr-xr-x 1 benesch admin 26 Jul  7 22:22 /usr/local/opt/python@3.9 -> ../Cellar/python@3.9/3.9.6
```

**Comment by benesch** [comment]
I sent #419 with a proposed fix. z
