### ISSUE TITLE
dill unable to load instance of dict derived class -- attributes declared in init not available

### ISSUE THREAD

**Issue by sandeep-gh** [uqfoundation/dill#429]
Serializing the addict library.  Its a small code so have copied it here itself. 
It has one attrribute __frozen. After pickle/depickle the attribute is no longer available. Otherwise, core functionality seems to work after depickle. 

My extension add two more attributes which are crtical to functioning and they break down in pickle/depickle. 

```
import copy
import dill as pickle

class Dict(dict):

    def __init__(__self, *args, **kwargs):
        print ("init")
        object.__setattr__(__self, '__parent', kwargs.pop('__parent', None))
        object.__setattr__(__self, '__key', kwargs.pop('__key', None))
        object.__setattr__(__self, '__frozen', False)
        for arg in args:
            if not arg:
                continue
            elif isinstance(arg, dict):
                for key, val in arg.items():
                    __self[key] = __self._hook(val)
            elif isinstance(arg, tuple) and (not isinstance(arg[0], tuple)):
                __self[arg[0]] = __self._hook(arg[1])
            else:
                for key, val in iter(arg):
                    __self[key] = __self._hook(val)

        for key, val in kwargs.items():
            __self[key] = __self._hook(val)

    def __setattr__(self, name, value):
        print ("setattr ", name)
        if hasattr(self.__class__, name):
            raise AttributeError("'Dict' object attribute "
                                 "'{0}' is read-only".format(name))
        else:
            self[name] = value

    def __setitem__(self, name, value):
        print ("setitem ", name)
        isFrozen = (hasattr(self, '__frozen') and
                    object.__getattribute__(self, '__frozen'))
        print ("setitem 2 ", name)
        if isFrozen and name not in super(Dict, self).keys():
                raise KeyError(name)
        print ("setitem 3 ", name)            
        super(Dict, self).__setitem__(name, value)
        try:
            print ("setitem 5 ", name)            
            p = object.__getattribute__(self, '__parent')
            print ("setitem 7 ", name)            
            key = object.__getattribute__(self, '__key')
        except AttributeError:
            p = None
            key = None
            print ("setitem 6 ", name)            
        if p is not None:
            print ("setitem 4 ", name)
            p[key] = self
            object.__delattr__(self, '__parent')
            object.__delattr__(self, '__key')

    def __add__(self, other):
        print ("add ", name)
        if not self.keys():
            return other
        else:
            self_type = type(self).__name__
            other_type = type(other).__name__
            msg = "unsupported operand type(s) for +: '{}' and '{}'"
            raise TypeError(msg.format(self_type, other_type))

    @classmethod
    def _hook(cls, item):
        print ("hook")
        if isinstance(item, dict):
            return cls(item)
        elif isinstance(item, (list, tuple)):
            return type(item)(cls._hook(elem) for elem in item)
        return item

    def __getattr__(self, item):
        print ("getattr ", item)
        return self.__getitem__(item)

    def __missing__(self, name):
        print ("missing ", name)
        if object.__getattribute__(self, '__frozen'):
            print ("raised keyerror")
            raise KeyError(name)
        print ("returning an instance of the class", self.__class__, name)
        return self.__class__(__parent=self, __key=name)

    def __delattr__(self, name):
        del self[name]

    def to_dict(self):
        base = {}
        for key, value in self.items():
            if isinstance(value, type(self)):
                base[key] = value.to_dict()
            elif isinstance(value, (list, tuple)):
                base[key] = type(value)(
                    item.to_dict() if isinstance(item, type(self)) else
                    item for item in value)
            else:
                base[key] = value
        return base

    def copy(self):
        return copy.copy(self)

    def deepcopy(self):
        return copy.deepcopy(self)

    def __deepcopy__(self, memo):
        other = self.__class__()
        memo[id(self)] = other
        for key, value in self.items():
            other[copy.deepcopy(key, memo)] = copy.deepcopy(value, memo)
        return other

    def update(self, *args, **kwargs):
        print ("calling update ", args, " ", kwargs)
        other = {}
        if args:
            if len(args) > 1:
                raise TypeError()
            other.update(args[0])
        other.update(kwargs)
        for k, v in other.items():
            if ((k not in self) or
                (not isinstance(self[k], dict)) or
                (not isinstance(v, dict))):
                self[k] = v
            else:
                self[k].update(v)

    def __getnewargs__(self):
        print ("Hgetnewargs")
        return tuple(self.items())

    def __getstate__(self):
        print ("Hgetstate")
        return self

    def __setstate__(self, state):
        print ("Hsetstate ", state)
        self.update(state)

    def __or__(self, other):
        print ("Hpr")
        if not isinstance(other, (Dict, dict)):
            return NotImplemented
        new = Dict(self)
        new.update(other)
        return new

    def __ror__(self, other):
        print ("Hror")
        if not isinstance(other, (Dict, dict)):
            return NotImplemented
        new = Dict(other)
        new.update(self)
        return new

    def __ior__(self, other):
        print ("Hior")
        self.update(other)
        return self

    def setdefault(self, key, default=None):
        if key in self:
            return self[key]
        else:
            self[key] = default
            return default

    def freeze(self, shouldFreeze=True):
        object.__setattr__(self, '__frozen', shouldFreeze)
        for key, val in self.items():
            if isinstance(val, Dict):
                val.freeze(shouldFreeze)

    def unfreeze(self):
        self.freeze(False)


x = Dict()
x.a= 1
print (x.__frozen)
with open("/tmp/t.p", "wb") as fh:
    pickle.dump(x, fh)

import time

time.sleep(1)
print ("Loading")
with open("/tmp/t.p", "rb") as fh:
    y = pickle.load(fh)
print (y.__frozen)

```
Thanks for taking a look.

**Comment by sandeep-gh** [comment]
will create a simpler code that exhibit this behaviour

**Comment by mmckerns** [comment]
Ok sounds good.  feel free to reopen this ticket with the simpler code or start a new ticket

**Comment by sandeep-gh** [comment]
Reopening the issue with updated test case.

**Comment by mmckerns** [comment]
running with python3.7, I get something like this as output.
```
init
setattr  a
setitem  a
setitem 2  a
setitem 3  a
setitem 5  a
setitem 7  a
False
Hgetnewargs
Hgetstate
Loading
setitem  a
getattr  __frozen
missing  __frozen
setitem 2  a
setitem 3  a
setitem 5  a
setitem 6  a
Hsetstate  {'a': 1}
calling update  ({'a': 1},)   {}
setitem  a
getattr  __frozen
missing  __frozen
setitem 2  a
setitem 3  a
setitem 5  a
setitem 6  a
setattr  __class__
getattr  __frozen
missing  __frozen
Traceback (most recent call last):
  File "test.py", line 196, in <module>
    print (y.__frozen)
  File "test.py", line 79, in __getattr__
    return self.__getitem__(item)
  File "test.py", line 83, in __missing__
    if object.__getattribute__(self, '__frozen'):
AttributeError: 'Dict' object has no attribute '__frozen'
```
Is this roughly what you are seeing?

Note that I can also use `dumps` and `loads` and still get the same error.

Also, __frozen is not really declared in init... and you are doing something weird with init, as you are using `__self` there. Note also that you are not calling init for the dict (i.e. didn't use super).

If I hardwire  `__self.__frozen = False` in init, it still fails.  If I replace `__self` with `self`, is also still fails.  Is there a reason you aren't calling super in init to instantiate the dict properly?  Anyway, there's a lot going on here...

Can you reduce this example down a bit further, and maybe remove some of the unusual stuff that may not be necessary?  There's still a lot of code here, and maybe removing some of it and seeing where behavior changes could give you some clues.
