### ISSUE TITLE
CodeType expects very different args in python 3.11

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/dill#432]
```
$ python test_check.py 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mmckerns/lib/python3.11/site-packages/dill-0.3.5.dev0-py3.11.egg/dill/_dill.py", line 327, in loads
    return load(file, ignore, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mmckerns/lib/python3.11/site-packages/dill-0.3.5.dev0-py3.11.egg/dill/_dill.py", line 313, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mmckerns/lib/python3.11/site-packages/dill-0.3.5.dev0-py3.11.egg/dill/_dill.py", line 525, in load
    obj = StockUnpickler.load(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mmckerns/lib/python3.11/site-packages/dill-0.3.5.dev0-py3.11.egg/dill/_dill.py", line 659, in _create_code
    if len(args) == 16: return CodeType(*args)
                               ^^^^^^^^^^^^^^^
TypeError: code expected at least 18 arguments, got 16
```

**Comment by mmckerns** [comment]
```
            args = (
                obj.co_argcount, obj.co_posonlyargcount,
                obj.co_kwonlyargcount, obj.co_nlocals, obj.co_stacksize,
                obj.co_flags, obj.co_code, obj.co_consts, obj.co_names,
                obj.co_varnames, obj.co_filename, obj.co_name, **obj.co_qualname,**
                obj.co_firstlineno, obj.co_lnotab,
                **obj.co_endlinetable, obj.co_columntable, obj.co_exceptiontable,**
                obj.co_freevars, obj.co_cellvars
        )
```

**Comment by DanielNoord** [comment]
Hi @mmckerns, thanks for finding and fixing this! I was wondering when the release of the next version is planned. We'd like to prepare our support for `3.11` in `pylint` and `dill` is one of our dependencies that is broken right now.

**Comment by mmckerns** [comment]
@DanielNoord: A new release is imminent.  We had some delays that pushed the release schedule back a few months, but it should be out before the end of April.

**Comment by DanielNoord** [comment]
@mmckerns Thanks for the reply! I'll keep an eye out then 😄
