### ISSUE TITLE
Dill sending TypeError when pickling nested functions

### ISSUE THREAD

**Issue by kurt-rhee** [uqfoundation/dill#435]
def test_outer(a):
        def test_inner(a):
            return a+1
        return a
    dill.dumps(test_outer)

Traceback (most recent call last):
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-24-ae7d65abc28d>", line 1, in <module>
    dill.dumps(test_outer)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/site-packages/dill/_dill.py", line 304, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/site-packages/dill/_dill.py", line 276, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/site-packages/dill/_dill.py", line 498, in dump
    StockPickler.dump(self, obj)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 487, in dump
    self.save(obj)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/site-packages/dill/_dill.py", line 1493, in save_function
    pickler.save_reduce(_create_function, (obj.__code__,
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 692, in save_reduce
    save(args)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 901, in save_tuple
    save(element)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/site-packages/dill/_dill.py", line 1176, in save_instancemethod0
    pickler.save_reduce(MethodType, (obj.__func__, obj.__self__), obj=obj)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 692, in save_reduce
    save(args)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 886, in save_tuple
    save(element)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/home/skrhee/miniconda3/envs/hdmodeler/lib/python3.8/pickle.py", line 578, in save
    rv = reduce(self.proto)
TypeError: cannot pickle 'sqlite3.Connection' object

**Comment by mmckerns** [comment]
Essentially, this exact test code is run in the dill tests, and passes for all versions of python... so I expect it has to be something in your environment. Let's try to figure that out.

Maybe you can run your code again using `dill.detect.trace(True)`?
