### ISSUE TITLE
Dill fails to pickle types of some builtins (ellipsis literal and NotImplemented)

### ISSUE THREAD

**Issue by lexnasser** [uqfoundation/dill#441]
When attempting to dump `type(...)`, dill raises a PicklingError via pickle:
```
>>> dill.dumps(type(...))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/dill/_dill.py", line 273, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "/opt/homebrew/lib/python3.9/site-packages/dill/_dill.py", line 267, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/opt/homebrew/lib/python3.9/site-packages/dill/_dill.py", line 454, in dump
    StockPickler.dump(self, obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 487, in dump
    self.save(obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/opt/homebrew/lib/python3.9/site-packages/dill/_dill.py", line 1390, in save_type
    StockPickler.save_global(pickler, obj, name=name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 1070, in save_global
    raise PicklingError(
_pickle.PicklingError: Can't pickle <class 'ellipsis'>: it's not found as builtins.ellipsis
>>> dill.dumps(type(...))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/dill/_dill.py", line 273, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "/opt/homebrew/lib/python3.9/site-packages/dill/_dill.py", line 267, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/opt/homebrew/lib/python3.9/site-packages/dill/_dill.py", line 454, in dump
    StockPickler.dump(self, obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 487, in dump
    self.save(obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/opt/homebrew/lib/python3.9/site-packages/dill/_dill.py", line 1390, in save_type
    StockPickler.save_global(pickler, obj, name=name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 1070, in save_global
    raise PicklingError(
_pickle.PicklingError: Can't pickle <class 'ellipsis'>: it's not found as builtins.ellipsis
```

The same error occurs if called by its module name:
```
>>> dill.dumps(type(builtins.Ellipsis))
... Can't pickle <class 'ellipsis'>: it's not found as builtins.ellipsis
```

---

A similar issue can be found with the following call:
```
>>> dill.dumps(type(NotImplemented))
... Can't pickle <class 'NotImplementedType'>: it's not found as builtins.NotImplementedType
```

Referring to the PicklingErrors, I believe this is because the class names differs from the variable names ("Ellipsis" != "ellipsis", "NotImplemented" != "NotImplementedType"), so the module lookup by (variable) name fails in the save function in pickle (https://github.com/python/cpython/blob/3.10/Lib/pickle.py#L535).

**Comment by lexnasser** [comment]
It actually seems that pickle supports this logic (https://github.com/python/cpython/blob/3.10/Lib/pickle.py#L1122-L1129), but it is not used by dill?

**Comment by lexnasser** [comment]
I also see that this is referenced in dill here: https://github.com/uqfoundation/dill/blob/master/dill/_objects.py#L266

**Comment by mmckerns** [comment]
`dill` can serialize an `Ellipsis` and a `NotImplemented` -- the instances but apparently not the class objects.  I assume this is because of serializing the instance doesn't lean on the class.  I can only assume that these two class objects haven't been `formally` attempted recently.

I see that they work in 2.7:
```
Python 2.7.18 (default, Nov 11 2021, 13:45:52) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> dill.dumps(type(Ellipsis))
'\x80\x02cdill._dill\n_load_type\nq\x00U\x0cEllipsisTypeq\x01\x85q\x02Rq\x03.'
>>> dill.dumps(type(NotImplemented))
'\x80\x02cdill._dill\n_load_type\nq\x00U\x12NotImplementedTypeq\x01\x85q\x02Rq\x03.'
```
but fail in 3.6+.  I'm guessing that they were changed somewhere along the way in 3.x, and  there's no assert on these class objects, so it wasn't raised until now.

**Comment by mmckerns** [comment]
Yeah, the solution is either to explicitly add the callout you noted above for those specific class objects in `pickle` when saving a builtin class object, or filter or those two types and punt to `pickle`.  Shouldn't be too hard to add that.

**Comment by mmckerns** [comment]
I'm happy to take a PR on it if you are interested...

**Comment by lexnasser** [comment]
@mmckerns That'd be great - thanks for the help!
