### ISSUE TITLE
Python3.6, _pickle.PicklingError

### ISSUE THREAD

**Issue by qq745639151** [uqfoundation/dill#457]
In Python3.6, when I try to execute the following code, it raise a Exception. But in Python3.7, the code works well.

```python
import dill
from typing import Callable, TypeVar, cast

FUNC1 = TypeVar("FUNC1", bound=Callable[..., object])


class TestCase:
    def __init__(self, func: FUNC1):
        self.func = cast(func, FUNC1)


def func():
    return "hello"


dill.dumps(TestCase(func))
```
the program raise exception:
```python
Traceback (most recent call last):
  File "F:/GitCode/gitlab/PiStarFramework_merge/test_Dill.py", line 16, in <module>
    dill.dumps(TestCase(func))
  File "C:\Python\Python36\lib\site-packages\dill\_dill.py", line 304, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "C:\Python\Python36\lib\site-packages\dill\_dill.py", line 276, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "C:\Python\Python36\lib\site-packages\dill\_dill.py", line 498, in dump
    StockPickler.dump(self, obj)
  File "C:\Python\Python36\lib\pickle.py", line 409, in dump
    self.save(obj)
  File "C:\Python\Python36\lib\pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python\Python36\lib\pickle.py", line 634, in save_reduce
    save(state)
  File "C:\Python\Python36\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python\Python36\lib\site-packages\dill\_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Python\Python36\lib\pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Python\Python36\lib\pickle.py", line 852, in _batch_setitems
    save(v)
  File "C:\Python\Python36\lib\pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python\Python36\lib\pickle.py", line 634, in save_reduce
    save(state)
  File "C:\Python\Python36\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python\Python36\lib\pickle.py", line 736, in save_tuple
    save(element)
  File "C:\Python\Python36\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python\Python36\lib\site-packages\dill\_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Python\Python36\lib\pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Python\Python36\lib\pickle.py", line 847, in _batch_setitems
    save(v)
  File "C:\Python\Python36\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python\Python36\lib\site-packages\dill\_dill.py", line 1439, in save_type
    StockPickler.save_global(pickler, obj, name=name)
  File "C:\Python\Python36\lib\pickle.py", line 927, in save_global
    (obj, module_name, name))
_pickle.PicklingError: Can't pickle typing.Callable[..., object]: it's not the same object as typing.Callable
```
But In Python3.7 and later, it works well

**Comment by mmckerns** [comment]
I'm closing this, because as of Feb 21, python 3.6 is no longer supported.  See d3d99065869537821bfbf28d50b47f41b08e92d9.
