### ISSUE TITLE
linux python3.8  logging cannot be pickled

### ISSUE THREAD

**Issue by qq745639151** [uqfoundation/dill#474]

**Comment by qq745639151** [comment]
"python3.8/lib/python3.8/logging/__init__.py", line 1735, in __reduce__ raise pickle.PicklingError('logger cannot be pickled')

**Comment by mmckerns** [comment]
Is the above example the same as what you are seeing?

**Comment by leogama** [comment]
Doesn't work for me on either Python 3.7 or Python 3.11a (works on Python 2.7 though). Are you suggesting that dill adds support for `logging.Logger`? What is the use case?

**Comment by qq745639151** [comment]
> 

yes， it is

**Comment by qq745639151** [comment]
Python 3.8.7 (default, Jun  3 2021, 15:26:29) 
[GCC 4.8.5 20150623 (EulerOS 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> log = logging.Logger('foo')
>>> import dill
>>> s = dill.dumps(log)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/devcloud/python3.8/lib/python3.8/site-packages/dill/_dill.py", line 304, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "/home/devcloud/python3.8/lib/python3.8/site-packages/dill/_dill.py", line 276, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/home/devcloud/python3.8/lib/python3.8/site-packages/dill/_dill.py", line 498, in dump
    StockPickler.dump(self, obj)
  File "/home/devcloud/python3.8/lib/python3.8/pickle.py", line 487, in dump
    self.save(obj)
  File "/home/devcloud/python3.8/lib/python3.8/pickle.py", line 578, in save
    rv = reduce(self.proto)
  File "/home/devcloud/python3.8/lib/python3.8/logging/__init__.py", line 1735, in __reduce__
    raise pickle.PicklingError('logger cannot be pickled')
_pickle.PicklingError: logger cannot be pickled

**Comment by qq745639151** [comment]
> Doesn't work for me on either Python 3.7 or Python 3.11a (works on Python 2.7 though). Are you suggesting that dill adds support for `logging.Logger`? What is the use case?

I have tried it in Python 3.7.7. It works.
Python 3.7.7 (default, Jun  4 2020, 09:08:42) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> log = logging.Logger("foo")
>>> import dill
>>> dill.dumps(log)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/dill/_dill.py", line 304, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "/usr/local/lib/python3.7/site-packages/dill/_dill.py", line 276, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/usr/local/lib/python3.7/site-packages/dill/_dill.py", line 498, in dump
    StockPickler.dump(self, obj)
  File "/usr/local/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/usr/local/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1661, in __reduce__
    raise pickle.PicklingError('logger cannot be pickled')
_pickle.PicklingError: logger cannot be pickled

**Comment by leogama** [comment]
Observation: adding support for loggers implies to also add support for logging handlers, filters and formatters. And even if the operation succeeds, if the original logger had a parent logger or if was part of a logging manager, the unpickled logger won't be able to work cooperatively anymore.

Though if the logger is managed by `Logger.manager` or other manager, it would be possible to save the manager as a global and just the logger's name and internal state, and then get it back with `manager.getLogger(name)` and restore its state when unpickling.

**Comment by leogama** [comment]
CPython discussions about the issue: https://github.com/python/cpython/issues/74705 and https://github.com/python/cpython/pull/1956

It seems that they did something in the line of what I said. If the logger was created by `logging.getLogger()` it is saved by name, otherwise it raises an exception. But the state is not restored.

**Comment by mmckerns** [comment]
note that the default logger works:
```
>>> import logging
>>> log = logging.getLogger()
>>> import dill
>>> dill.dumps(log)
b'\x80\x03clogging\ngetLogger\nq\x00)Rq\x01.'
```
