### ISSUE TITLE
Unpicklable objects defined in doctests interfere with serialization of lambdas

### ISSUE THREAD

**Issue by JoshRosen** [uqfoundation/dill#50]
I found another example where Dill fails to pickle objects when running under doctest.  This is a one-line addition to my test-case in #18.

I'm using Python 2.7.6 and Dill eb122e6eb00dcfa9704ffa692fc7a14850867185. 

/cc @distobj

```python
import dill as pickle
import doctest

pickle.dill._trace(1)

class SomeUnreferencedUnpicklableClass(object):
    def __reduce__(self):
        raise Exception

unpicklable = SomeUnreferencedUnpicklableClass()

# This works fine outside of Doctest:
serialized = pickle.dumps(lambda x: x)

# This fails because it tries to pickle the unpicklable object:
def tests():
    """
    >>> unpicklable = SomeUnreferencedUnpicklableClass()  # <-- Added since #18
    >>> serialized = pickle.dumps(lambda x: x)
    """
    return

print "\n\nRunning Doctest:"
doctest.testmod()
```

Output:

```
F1: <function <lambda> at 0x101f8f848>
F2: <function _create_function at 0x101c96d70>
Co: <code object <lambda> at 0x100474ab0, file "dillbugtwo.py", line 13>
F2: <function _unmarshal at 0x101c96c08>
D1: <dict object at 0x10031ba20>
D2: <dict object at 0x101da9de0>


Running Doctest:
F1: <function <lambda> at 0x101f8f938>
F2: <function _create_function at 0x101c96d70>
Co: <code object <lambda> at 0x101f369b0, file "<doctest __main__.tests[1]>", line 1>
F2: <function _unmarshal at 0x101c96c08>
D2: <dict object at 0x102206120>
F1: <function tests at 0x101f8f848>
Co: <code object tests at 0x100474e30, file "dillbugtwo.py", line 16>
D1: <dict object at 0x10031ba20>
D2: <dict object at 0x10222e940>
**********************************************************************
File "dillbugtwo.py", line 19, in __main__.tests
Failed example:
    serialized = pickle.dumps(lambda x: x)
Exception raised:
    Traceback (most recent call last):
      File "/Users/joshrosen/anaconda/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest __main__.tests[1]>", line 1, in <module>
        serialized = pickle.dumps(lambda x: x)
      File "/Users/joshrosen/anaconda/lib/python2.7/site-packages/dill-0.2.2.dev-py2.7.egg/dill/dill.py", line 165, in dumps
        dump(obj, file, protocol, byref)
      File "/Users/joshrosen/anaconda/lib/python2.7/site-packages/dill-0.2.2.dev-py2.7.egg/dill/dill.py", line 158, in dump
        pik.dump(obj)
      File "/Users/joshrosen/anaconda/lib/python2.7/pickle.py", line 224, in dump
        self.save(obj)
      File "/Users/joshrosen/anaconda/lib/python2.7/pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
      File "/Users/joshrosen/anaconda/lib/python2.7/site-packages/dill-0.2.2.dev-py2.7.egg/dill/dill.py", line 506, in save_function
        obj.__dict__), obj=obj)
      File "/Users/joshrosen/anaconda/lib/python2.7/pickle.py", line 401, in save_reduce
        save(args)
      File "/Users/joshrosen/anaconda/lib/python2.7/pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
      File "/Users/joshrosen/anaconda/lib/python2.7/pickle.py", line 562, in save_tuple
        save(element)
      File "/Users/joshrosen/anaconda/lib/python2.7/pickle.py", line 286, in save
        f(self, obj) # Call unbound method with explicit self
      File "/Users/joshrosen/anaconda/lib/python2.7/site-packages/dill-0.2.2.dev-py2.7.egg/dill/dill.py", line 538, in save_module_dict
        StockPickler.save_dict(pickler, obj)
      File "/Users/joshrosen/anaconda/lib/python2.7/pickle.py", line 649, in save_dict
        self._batch_setitems(obj.iteritems())
      File "/Users/joshrosen/anaconda/lib/python2.7/pickle.py", line 681, in _batch_setitems
        save(v)
      File "/Users/joshrosen/anaconda/lib/python2.7/pickle.py", line 306, in save
        rv = reduce(self.proto)
      File "dillbugtwo.py", line 8, in __reduce__
        raise Exception
    Exception
**********************************************************************
1 items had failures:
   1 of   2 in __main__.tests
***Test Failed*** 1 failures.
```

**Comment by mmckerns** [comment]
As of fadbffc2b688aa99d3ba29015c4cdbef463bf565, this works with `recurse=True`.
