### ISSUE TITLE
loading fails for typing.Tuple[()]

### ISSUE THREAD

**Issue by ryanthompson591** [uqfoundation/dill#517]
How to reproduce:

Run this code with 0.3.4 you will see it pass.
Run in 0.3.5.1 and you will see it fail.

```
import dill

from typing import Union, Tuple

FeatureValueType = Union[str, int, float]  # pylint: disable=invalid-name
SingletonSliceKeyType = Tuple[str, FeatureValueType]  # pylint: disable=invalid-name
A_TYPE = Union[Tuple[()], Tuple[SingletonSliceKeyType, ...]]

def a_function() -> A_TYPE:
  return ('string', 'feature_value_type')

serialized = dill.dumps(a_function)
loaded = dill.loads(serialized)

print(loaded())
```

I get the following error in 0.3.5.1

```
Traceback (most recent call last):
  File "/Users/ryanthompson/PycharmProjects/learningProjects/dill_regression/regression_test.py", line 13, in <module>
    loaded = dill.loads(serialized)
  File "/Users/ryanthompson/.pyenv/versions/3.8.11/lib/python3.8/site-packages/dill/_dill.py", line 387, in loads
    return load(file, ignore, **kwds)
  File "/Users/ryanthompson/.pyenv/versions/3.8.11/lib/python3.8/site-packages/dill/_dill.py", line 373, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/Users/ryanthompson/.pyenv/versions/3.8.11/lib/python3.8/site-packages/dill/_dill.py", line 646, in load
    obj = StockUnpickler.load(self)
  File "/Users/ryanthompson/.pyenv/versions/3.8.11/lib/python3.8/typing.py", line 804, in __getitem__
    return self.__getitem_inner__(params)
  File "/Users/ryanthompson/.pyenv/versions/3.8.11/lib/python3.8/typing.py", line 261, in inner
    return func(*args, **kwds)
  File "/Users/ryanthompson/.pyenv/versions/3.8.11/lib/python3.8/typing.py", line 830, in __getitem_inner__
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/ryanthompson/.pyenv/versions/3.8.11/lib/python3.8/typing.py", line 830, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/Users/ryanthompson/.pyenv/versions/3.8.11/lib/python3.8/typing.py", line 149, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Tuple[t0, t1, ...]: each t must be a type. Got ().
```

**Comment by mmckerns** [comment]
The message in the TypeError says that you should be passing a type, and not an expression (i.e. `()`).
If instead you do this, it works as expected:
```
>>> import dill
>>> from typing import Tuple
>>> t = Tuple[tuple]
>>> s = dill.dumps(t)
>>> dill.loads(s)
typing.Tuple[tuple]
```
Is there a reason you are passing a tuple instance instead of a tuple?

**Comment by mmckerns** [comment]
Yeah, I just found this is indeed intentional.  So, definitely needs support.

**Comment by mmckerns** [comment]
Here's what I'm seeing from `dill-0.3.4`:
```
>>> import dill
>>> from typing import Tuple
>>> t = Tuple[()]
>>> t
typing.Tuple[()]
>>> s = dill.dumps(t)
>>> dill.loads(s)
typing.Tuple
>>> 
```
So, essentially it didn't serialize correctly.

**Comment by mmckerns** [comment]
The old trace (note it's python 3.6, but that "shouldn't matter"):
```
>>> dill.detect.trace(True)
>>> s = dill.dumps(t)
T2: typing.Tuple[()]
F2: <function _create_type at 0x10cd36e18>
# F2
T4: <class 'typing.TupleMeta'>
# T4
T4: typing.Tuple
# T4
T1: <class 'tuple'>
F2: <function _load_type at 0x10cd36d90>
# F2
# T1
D2: <dict object at 0x10cdb7a20>
Cm: <staticmethod object at 0x10cd84240>
T1: <class 'staticmethod'>
# T1
F1: <function Tuple.__new__ at 0x10cd82598>
F2: <function _create_function at 0x10cd36ea0>
# F2
Co: <code object __new__ at 0x10cd63c00, file "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 1291>
F2: <function _create_code at 0x10cd36f28>
# F2
# Co
D4: <dict object at 0x10c9c3ea0>
# D4
D2: <dict object at 0x10cd64c60>
# D2
# F1
# Cm
T1: <class 'frozenset'>
# T1
T4: <class '_weakrefset.WeakSet'>
# T4
D2: <dict object at 0x10cd87120>
T1: <class 'set'>
# T1
F1: <function WeakSet.__init__.<locals>._remove at 0x10cd82620>
Co: <code object _remove at 0x10c795c90, file "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_weakrefset.py", line 38>
# Co
D4: <dict object at 0x10c791750>
# D4
R1: <weakref at 0x10cd7b868; to 'WeakSet' at 0x10cd84278>
F2: <function _create_weakref at 0x10cd31620>
# F2
# R1
D2: <dict object at 0x10cd64e58>
# D2
# F1
# D2
D2: <dict object at 0x10cd87168>
F1: <function WeakSet.__init__.<locals>._remove at 0x10cd826a8>
D4: <dict object at 0x10c791750>
# D4
R1: <weakref at 0x10cd7b8b8; to 'WeakSet' at 0x10cd842e8>
# R1
D2: <dict object at 0x10cd64dc8>
# D2
# F1
# D2
D2: <dict object at 0x10cd871b0>
F1: <function WeakSet.__init__.<locals>._remove at 0x10cd82730>
D4: <dict object at 0x10c791750>
# D4
R1: <weakref at 0x10cd7b908; to 'WeakSet' at 0x10cd84358>
# R1
D2: <dict object at 0x10cd64f30>
# D2
# F1
# D2
T1: <class 'object'>
# T1
F1: <function _make_subclasshook.<locals>.__extrahook__ at 0x10cdbc268>
Co: <code object __extrahook__ at 0x10cd5d4b0, file "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 889>
# Co
D4: <dict object at 0x10c9c3ea0>
# D4
Ce2: <cell at 0x10cd33cd8: TupleMeta object at 0x7fa01aae4858>
F2: <function _create_cell at 0x10cd31378>
# F2
# Ce2
D2: <dict object at 0x10cd64d38>
# D2
# F1
# D2
B1: <built-in function getattr>
F2: <function _get_attr at 0x10cd319d8>
# F2
# B1
M2: <module 'dill._dill' from '/Users/mmckerns/lib/python3.6/site-packages/dill-0.3.5.dev0-py3.6.egg/dill/_dill.py'>
# M2
B1: <built-in function setattr>
# B1
# T2
```
and the new trace:
```
>>> dill.detect.trace(True)
>>> s = dill.dumps(t)
```
(i.e. totally handled by `pickle.Pickler`).

**Comment by mmckerns** [comment]
This might be something that won't get fixed in python, as `typing.Tuple` is deprecated. See: https://docs.python.org/3/library/typing.html#typing.Tuple and https://peps.python.org/pep-0585.

... and empty tuple type pickling works on `builtins.tuple`:
```
>>> import pickle
>>> t = tuple[()]
>>> t
tuple[()]
>>> s = pickle.dumps(t)
>>> pickle.loads(s)
tuple[()]
>>>
```

**Comment by mmckerns** [comment]
Here's a potential workaround, and to me clearly seems to be a python bug:
```
>>> import pickle
>>> t = typing.Tuple[()]
>>> t
typing.Tuple[()]
>>> t = t.copy_with(())
>>> t
typing.Tuple[]
>>> s = pickle.dumps(t)
>>> pickle.loads(s)
typing.Tuple[()]
>>> typing.Tuple[]
  File "<stdin>", line 1
    typing.Tuple[]
                 ^
SyntaxError: invalid syntax
```

**Comment by tvalentyn** [comment]
Since typing.Tuple is deprecated, I would suggest to preserve the pickling behavior of 3.4 even if it less semantically precise, to have less breaking changes.

**Comment by mmckerns** [comment]
@tvalentyn: with the new `dill` shims module, we can preserve prior behavior so as to not break stored pickles.  Is that what you are looking for?  I'd argue that if there's a bugfix it should be applied (instead of preserving incorrect behavior), as long as stored pickles that were created before the change can be unpickled after the change.

**Comment by ryanthompson591** [comment]
What do you think about the idea of accepting a patch into the shims module to handle this edge case?

**Comment by ryanthompson591** [comment]
FYI: I did file an issue with python
https://github.com/python/cpython/issues/94245

**Comment by mmckerns** [comment]
From the `cpython` issue (ref above):
> We're not going to fix this for 3.9 and lower because those branches are in security fix-only mode, but we can still fix it on 3.10.

Hmm, so given that information and everything else above, I'm not sure how to best handle this yet.  Will need some thought...

**Comment by mmckerns** [comment]
I ended up adding special handling to serialize two cases of the `typing.Tuple`, and for everything else, punt back to `pickle`.  This is a change from the erroneous behavior (it worked by coincidence) in 0.3.4 and earlier. @tvalentyn: let me know if you think there needs to be some special handling for old pickles for Tuple[()]... as (shown above) they didn't actually serialize correctly.

**Comment by tvalentyn** [comment]
Thank you. Much appreciated. Left some comments.

**Comment by ryanthompson591** [comment]
Great. Just tried this out with dill at head and it works great.
