### ISSUE TITLE
Python 3.13.0b3: `test_detect.py`: `assert len(s) is len(a)` fails

### ISSUE THREAD

**Issue by mgorny** [uqfoundation/dill#668]
With Python 3.13.0b3:

```pytb
$ tox -e py313
.pkg: _optional_hooks> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_sdist> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_wheel> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: prepare_metadata_for_build_wheel> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: build_sdist> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta
py313: install_package> python -I -m pip install --force-reinstall --no-deps /tmp/dill/.tox/.tmp/package/2/dill-0.3.9.dev0.tar.gz
py313: commands[0]> .tox/py313/bin/python -m pip install .
Processing /tmp/dill
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: dill
  Building wheel for dill (pyproject.toml) ... done
  Created wheel for dill: filename=dill-0.3.9.dev0-py3-none-any.whl size=116420 sha256=8ec5680b73c6e4cced38b405f598995ac0ea9d2a00723c63187b67aee4f00e0e
  Stored in directory: /tmp/pip-ephem-wheel-cache-ljo7pesb/wheels/07/2c/cb/1b9d72d39710261d639bd94b649ef52ab21b8b837b3d16b253
Successfully built dill
Installing collected packages: dill
  Attempting uninstall: dill
    Found existing installation: dill 0.3.9.dev0
    Uninstalling dill-0.3.9.dev0:
      Successfully uninstalled dill-0.3.9.dev0
Successfully installed dill-0.3.9.dev0
py313: commands[1]> .tox/py313/bin/python dill/tests/__main__.py
.<function <lambda> at 0x7fabc2e993a0>
<function <lambda> at 0x7fb8e0098c20>
<function <lambda> at 0x7f24e9298c20>
<function <lambda> at 0x7f6f9fa98c20>
<function <lambda> at 0x7f515c098c20>
Traceback (most recent call last):
  File "/tmp/dill/dill/tests/test_detect.py", line 154, in <module>
    test_bad_things()
    ~~~~~~~~~~~~~~~^^
  File "/tmp/dill/dill/tests/test_detect.py", line 32, in test_bad_things
    assert len(s) is len(a) # TypeError (and possibly PicklingError)
           ^^^^^^^^^^^^^^^^
AssertionError
...F.......................
py313: exit 1 (2.96 seconds) /tmp/dill> .tox/py313/bin/python dill/tests/__main__.py pid=54358
  py313: FAIL code 1 (9.00=setup[3.81]+cmd[2.22,2.96] seconds)
  evaluation failed :( (9.07 seconds)
```

**Comment by mmckerns** [comment]
specifically addressed by #677
