### ISSUE TITLE
deserializing dill-serialized class instance with a property attribute renders the attribute unreadable

### ISSUE THREAD

**Issue by lebedov** [uqfoundation/dill#81]
Deserialization of a Python class instance serialized with dill that contains a property appears to render that property unreadable; running the following the code with Python 2.7.9 and dill 0.2.2 raises an `AttributeError: unreadable attribute` on the last line. This problem doesn't occur when the class instance is serialized/deserialized with pickle. Why is this happening?

```
class Foo(object):
    def __init__(self):
        self._data = 1 

    @property
    def data(self):
        return self._data

    @data.setter
    def data(self, x): 
        self._data = x 

import dill

with open('Foo.dill', 'w') as f:
    dill.dump(Foo(), f)

with open('Foo.dill', 'r') as f:
    f = dill.load(f)

print f.data
```

**Comment by matsjoyce** [comment]
Were you using pickle when Foo was in a module?

**Comment by lebedov** [comment]
@matsjoyce: if you were referring to the working situation with pickle that I alluded to, I just replaced dill with pickle in the above example.

**Comment by matsjoyce** [comment]
Yup, just seen that. Its wierd:
```
Python 3.4.2 (default, Jan 12 2015, 11:38:40) 
[GCC 4.9.2 20141224 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> dill.dill._trace(1)
>>> class Foo:
...  @property
...  def f(self): return "hi"
... 
>>> Foo().f
'hi'
>>> FooS = dill.loads(dill.dumps(Foo))
T2: <class '__main__.Foo'>
F2: <function _create_type at 0x7fb6cb83bbf8>
T1: <class 'type'>
F2: <function _load_type at 0x7fb6cb83bb70>
T1: <class 'object'>
D2: <dict object at 0x7fb6d0a82488>
T1: <class 'property'>
>>> FooS().f
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: unreadable attribute
>>> import pickle
>>> FooP = pickle.loads(pickle.dumps(Foo))
>>> FooP().f
'hi'
```

The interesting bit is `T1: <class 'property'>`, as I'm not quite sure why that appears, as pickle handles `dict`s in D2 mode.

**Comment by matsjoyce** [comment]
```
>>> pickle.dumps(Foo)
b'\x80\x03c__main__\nFoo\nq\x00.'
```
So pickle is not doing anything special.
This reproduces the problem:
```
>>> Foo.f=property()
>>> Foo().f
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: unreadable attribute
```
So the property must be serialised without the constructor arguments.

pickletools:
```
  108: X            BINUNICODE '__module__'
  123: q            BINPUT     11
  125: X            BINUNICODE '__main__'
  138: q            BINPUT     12
  140: X            BINUNICODE 'f'
  146: q            BINPUT     13
  148: h            BINGET     1
  150: X            BINUNICODE 'property'
  163: q            BINPUT     14
  165: \x85         TUPLE1
  166: q            BINPUT     15
  168: R            REDUCE
  169: q            BINPUT     16
  171: )            EMPTY_TUPLE
  172: \x81         NEWOBJ
  173: q            BINPUT     17
  175: X            BINUNICODE '__doc__'
  187: q            BINPUT     18
  189: N            NONE
  190: u            SETITEMS   (MARK at 107)
```
So no constructor arguments.

**Comment by matsjoyce** [comment]
Adding:
```
@dill.register(property)
def save_property(pickler, obj):
    pickler.save_reduce(property, (obj.fget, obj.fset, obj.fdel), obj=obj)
```
Before pickling makes it work. @mmckerns Is this worth patching in, maybe with `log.info("Pr: %s" % obj)`?

**Comment by lebedov** [comment]
Confirming that the fix works.

**Comment by matsjoyce** [comment]
And this should (theoretically) be compatible with 2.2+, so no version checks needed.

**Comment by mmckerns** [comment]
@matsjoyce: definitely worth it.  You did the hard work, you want to do the honors?

**Comment by matsjoyce** [comment]
I wouldn't call it hard work, but sure!

**Comment by mmckerns** [comment]
Thanks.

**Comment by lebedov** [comment]
Thanks, guys! Much appreciated.
